x64_dbg_gui/Project/Src/Gui/CPUDisassembly.cpp, x64_dbg_gui/Project/Src/Utils/Configuration.cpp, x64_dbg_gui/Project/prebuildStep.bat
As previously discussed please ignore any changes from me on the 	Update prebuildStep.bat
I have just added a simple commit to add some functionality . It's a minor change but for anyone that wants to just copy an address ,  I have added the keyboard command Alt+INS to copy an address change this if you feel it it should be done differently. Also this remains customize able through the shortcuts menu.
=> Added shortcut to just copy Address

x64_dbg_exe/resource.rc, x64_dbg_gui/Project/afterbuildStep.bat, x64_dbg_gui/Project/prebuildStep.bat
=> afxres.h doesnt always exist on system (if you dont have MFC installed)

x64_dbg_dbg/memory.cpp
bug only affected debug build, see #396
=> Fix zero termination

x64_dbg_gui/Project/Src/Gui/AttachDialog.cpp, x64_dbg_gui/Project/Src/Gui/AttachDialog.ui
Attach window previously had a fixed size (as does ollydbg for that
matter), which made finding the right process in some cases difficult.
=> Make attach window resizable

src/gui/Src/BasicView/HexDump.cpp, src/gui/Src/BasicView/HexDump.h, src/gui/Src/BasicView/SearchListView.cpp, src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/CPUDump.h, src/gui/Src/Gui/CPUInfoBox.cpp, src/gui/Src/Gui/CPUInfoBox.h, src/gui/Src/Gui/CPUMultiDump.cpp, src/gui/Src/Gui/CPUMultiDump.h, src/gui/Src/Gui/CPUWidget.cpp, src/gui/Src/Gui/CPUWidget.h, src/gui/Src/Gui/SymbolView.cpp, src/gui/Src/Gui/SymbolView.h, src/gui/Src/Gui/TabBar.cpp, src/gui/Src/Gui/TabBar.h, src/gui/Src/Gui/TabWidget.cpp, src/gui/Src/Gui/TabWidget.h, src/gui/x64dbg.pro
Added Multiple Dump window with abiltiy to choose in what to dump to follow (choice available only in multidump window)
Added ability to search within module list in the Symbols tab
Added double click behavior in InfoBox : not the "best" way to do it as it relies on the text shown in the infobox ("Jump to..", last row double clicked = follow EIP in dump).
=> Herz3h dev

src/bridge/bridgemain.cpp, src/bridge/bridgemain.h, src/dbg/x64_dbg.cpp, src/gui/Src/Bridge/Bridge.cpp, src/gui/Src/Bridge/Bridge.h, src/gui/Src/Gui/CommandLineEdit.cpp, src/gui/Src/Gui/CommandLineEdit.h, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h, src/gui/Src/Gui/TabWidget.h
Giving anyone a chance to view/test this before it gets merged into dev.
=> GUI Script Selector

src/bridge/bridgemain.cpp, src/bridge/bridgemain.h, src/gui/Src/Bridge/Bridge.cpp, src/gui/Src/Bridge/Bridge.h, src/gui/Src/Gui/CPUWidget.cpp, src/gui/Src/Gui/CPUWidget.h
I need this API to write a plugin to navigate back or forward in dump and stack window. Although this feature should be added in the main gui project, but there has a lot of work to do.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/513)
=> add new API: GuiGetFocusedCPUWindow

src/bridge/bridgemain.cpp, src/bridge/bridgemain.h, src/gui/Src/Bridge/Bridge.cpp, src/gui/Src/Bridge/Bridge.h, src/gui/Src/Gui/CPUWidget.cpp, src/gui/Src/Gui/CPUWidget.h
Reverts x64dbg/x64dbg#513
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/534)
=> Revert "add new API: GuiGetFocusedCPUWindow"

src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/MemoryMapView.cpp, src/gui/Src/Gui/MemoryMapView.h
Added ability to dump mapped memory to file
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/533)
=> Dump Memory Regions

src/gui/Src/BasicView/ReferenceView.cpp, src/gui/Src/BasicView/SearchListView.cpp, src/gui/Src/BasicView/SearchListView.h, src/gui/Src/Gui/SymbolView.cpp
Explained previously. TEST THIS FIRST!!!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/501)
=> Searchlistview

src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/CPUStack.h, src/gui/Src/Gui/CPUWidget.cpp
In regards to this issue: #520
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/547)
=> Stackview dump at Implementation

src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/CPUWidget.cpp, src/launcher/x64_dbg_launcher.cpp
In reference to comment in issue #538
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/552)
=> Add Icon to right click Context menu for shell extension.

src/launcher/x64_dbg_launcher.cpp
in reference to issue #538 Copy pasted previous PR that had conflicts due to delayed merge.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/556)
=> add desktop shortcuts to launcher

src/launcher/x64_dbg_launcher.cpp
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/557)
=> bug fix, release interfaces on early failure

src/gui/Src/Disassembler/QBeaEngine.cpp, src/gui/Src/Disassembler/capstone_gui.cpp
Fixes https://github.com/x64dbg/x64dbg/issues/315
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/576)
=> Fixed: X86_INS_LOOP shouldn't be of type Unconditional

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h
In reference to issue #354
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/578)
=> Follow in CPU in Disassembly view

src/dbg/module.cpp
Fixes https://github.com/x64dbg/x64dbg/issues/592
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/593)
=> Free module file handles upon cleanup

src/dbg/debugger.cpp
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/594)
=> Fixed removal of DLLLoader.exe

src/dbg/_global.cpp
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/595)
=> Fixed DirExists

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/622)
=> Fix titan-engine link

src/gui/Src/Gui/SettingsDialog.ui
Caused by Hi Resolution and Hi-DPI settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/641)
=> Fix UI bug in Setting dialog

src/gui/Src/Gui/MainWindow.h, src/gui/Src/main.cpp
mWindowMainTitle is set to `tr("x64dbg")` however it is not of type QString. #643
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/645)
=> Oops! Fix a compilation error introduced recently

src/dbg/debugger.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/657)
=> DBG: Fixed locking condition

src/bridge/bridgemain.cpp, src/dbg/instruction.cpp
Issue #649 Add module name to inter-modular call list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/667)
=> Add Module name to Intermodule call list in GUI. Addresses issue #649

src/bridge/bridgemain.cpp, src/dbg/instruction.cpp
Fix for issue #673 Used DbgModuleAt() and reverted change to DbgGetLabelAt()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/674)
=> fix for issue 673

src/launcher/x64_dbg_launcher.cpp
For issue #681
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/682)
=> Launcher now considers wow64 and creates appropriate desktop shortcut

src/gui/Src/Gui/EditFloatRegister.cpp, src/gui/Src/Gui/EditFloatRegister.h, src/gui/Src/Gui/EditFloatRegister.ui, src/gui/Src/Gui/RegistersView.cpp, src/gui/Src/Utils/HexValidator.cpp, src/gui/Src/Utils/HexValidator.h, src/gui/Src/Utils/LongLongValidator.cpp, src/gui/Src/Utils/LongLongValidator.h, src/gui/x64dbg.pro
#76 
The dialog appearance:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/695)
=> Edit floating-point register dialog

src/gui/Src/Gui/PatchDialog.cpp, src/gui/Src/Gui/PatchDialog.h
The project has switched to Qt5, I'll pull my work now so I can reconfigure my working environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/699)
=> Translate patch dialog, and prepare for new export format

src/dbg/debugger.cpp, src/dbg/debugger.h, src/dbg/debugger_commands.cpp
Fixed #564 fix pause.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/709)
=> DBG: fixed weird thread pause (#564)

src/gui/Src/Disassembler/capstone_gui.cpp
This pull request requires update in [https://github.com/x64dbg/capstone_wrapper/pull/2](url)
Implements intelligent nop. And moves unusual instructions into capstone_wrapper.
screenshot with NOP color set to white.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/718)
=> GUI: intelligent nop recognition

src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/BasicView/AbstractTableView.h
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/719)
=> Allow reordering the columns

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/HexEditDialog.cpp, src/gui/Src/Gui/HexEditDialog.h
Fixes #706.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/721)
=> GUI: Hide 'Keep size' checkbox while binary filling

src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/BasicView/AbstractTableView.h, src/gui/Src/BasicView/Disassembly.cpp, src/gui/Src/Gui/ColumnReorderDialog.cpp, src/gui/Src/Gui/ColumnReorderDialog.h, src/gui/Src/Gui/ColumnReorderDialog.ui, src/gui/Src/Gui/SettingsDialog.ui, src/gui/Src/Utils/CachedFontMetrics.h, src/gui/x64dbg.pro
Solving issue #722 
And add special handling of surrogates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/723)
=> Invalidate font size cache

src/gui/Src/BasicView/SearchListView.cpp, src/gui/Src/BasicView/SearchListView.h, src/gui/Src/Gui/AttachDialog.cpp, src/gui/Src/Gui/SymbolView.cpp
Fixed wired process refresh #697
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/728)
=> GUI: fixed wired process refresh (#697)

src/gui/Src/Gui/CPUDisassembly.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/735)
=> GUI: Add icons for menu->intermodular calls

src/dbg/debugger.cpp, src/dbg/debugger.h, src/dbg/debugger_commands.cpp, src/dbg/debugger_commands.h, src/dbg/x64_dbg.cpp, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h, src/gui/Src/Gui/MainWindow.ui
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/749)
=> Trace until condition

src/dbg/_dbgfunctions.cpp, src/dbg/_dbgfunctions.h, src/dbg/debugger.cpp, src/dbg/debugger.h, src/gui/Src/Gui/TimeWastedCounter.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/748)
=> Debug events counter

src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/Gui/ColumnReorderDialog.cpp, src/gui/Src/Gui/MemoryMapView.cpp, src/gui/Src/Gui/MemoryMapView.h, src/gui/Translations/x64dbg_zh_CN.ts
I can't reproduce your issue with column reordering in breakpoints view, however I spotted another issue related to column resizing. Please add that issue to the bug tracker with steps to reproduce the problem.
And I added menu items for memory allocation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/753)
=> Fix the issue with column resizing

src/bridge/bridgemain.cpp, src/dbg/debugger.cpp, src/dbg/stringformat.cpp, src/dbg/variable.cpp
and add script controllable conditional breakpoint support in advance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/803)
=> Fix some tiny issues

src/dbg/_exports.cpp, src/dbg/debugger.cpp, src/dbg/debugger.h, src/gui/Src/Gui/SettingsDialog.cpp, src/gui/Src/Gui/SettingsDialog.h, src/gui/Src/Gui/SettingsDialog.ui
commit selected feature on my local branch once it is stable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/807)
=> trace record during trace

src/bridge/x64_dbg_bridge.vcxproj, src/dbg/undocumented.h, src/dbg/x64_dbg_dbg.vcxproj, src/exe/x64_dbg_exe.vcxproj, src/gui/Src/Gui/StatusLabel.cpp, src/gui/x64dbg.pro
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/826)
=> Fixed label bug, guarded header file for window kit 8.1, debug builds build in non-release folder

src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.ui
Favourites -> &amp;Favourites
Manage Favourite Tools -> &amp;Manage Favourite Tools...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/844)
=> fix broken favourites keyboard shortcut

src/dbg/value.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/848)
=> fix issue #835

src/dbg/instruction.cpp, src/dbg/instruction.h, src/dbg/x64_dbg.cpp
I decided to use the msdn byteswap functions because it looks cleaner imo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/856)
=> Issue #852 add bswap command

src/bridge/_global.cpp, src/bridge/_global.h, src/bridge/bridgemain.cpp, src/bridge/bridgemain.h, src/dbg/_dbgfunctions.h, src/dbg/breakpoint.cpp, src/dbg/debugger.cpp, src/dbg/debugger.h, src/dbg/taskthread.h, src/dbg/thread.cpp, src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/BasicView/AbstractTableView.h, src/gui/Src/BasicView/Disassembly.cpp, src/gui/Src/BasicView/HistoryLineEdit.cpp, src/gui/Src/BasicView/HistoryLineEdit.h, src/gui/Src/BasicView/StdTable.cpp, src/gui/Src/BasicView/StdTable.h, src/gui/Src/Bridge/Bridge.cpp, src/gui/Src/Bridge/Bridge.h, src/gui/Src/Exports.h, src/gui/Src/Gui/CommandLineEdit.cpp, src/gui/Src/Gui/CommandLineEdit.h, src/gui/Src/Gui/LogView.cpp, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/SymbolView.cpp, src/gui/Src/Gui/ThreadView.cpp, src/gui/Src/Gui/TimeWastedCounter.cpp, src/gui/Src/Gui/TimeWastedCounter.h
Reverts x64dbg/x64dbg#834
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/859)
=> Revert "Added ability to roughly measure UI latency; code to try and maintain that latency at <50ms"

src/dbg/TraceRecord.cpp, src/dbg/debugger.cpp, src/dbg/watch.cpp, src/gui/Src/Gui/CPUInfoBox.cpp, src/gui/Src/Gui/CPUMultiDump.cpp, src/gui/Src/Gui/CPUMultiDump.h, src/gui/Src/Gui/MainWindow.ui
fix issue:
* #851 
* time goes too fast
* make watch view update async
* fix favourites hot key conflict
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/863)
=> fix issue #851

src/dbg/debugger_commands.cpp, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h, src/gui/Src/main.cpp, src/gui/Src/main.h
Adds a sub menu in the options menu to select language.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/878)
=> languages menu

src/bridge/bridgemain.h, src/dbg/thread.cpp, src/dbg/value.cpp, src/gui/Src/BasicView/StdTable.cpp, src/gui/Src/BasicView/StdTable.h, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/CPUSideBar.cpp, src/gui/Src/Gui/CPUSideBar.h, src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/CallStackView.cpp, src/gui/Src/Gui/CallStackView.h, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/ThreadView.cpp, src/gui/Src/Utils/Configuration.cpp, src/gui/Src/Utils/MenuBuilder.h, src/gui/Src/Utils/StringUtil.cpp, src/gui/Src/Utils/StringUtil.h, src/gui/Src/Utils/UpdateChecker.cpp
1. PEB and TEB symbols integrated
2. use MenuBuilder in CallStack view
3. new appearance of CPUSideBar ( #814 )
4. locale dependent compile date to string function
5. CPU Time in threads view ( #842 **might break plugins** )
6. temporarily disable update checker because jenkins is down.
7. other minor fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/885)
=> CPU Time in threads view

src/bridge/bridgemain.cpp, src/bridge/bridgemain.h, src/dbg/instruction.cpp, src/dbg/instruction.h, src/dbg/plugin_loader.cpp, src/dbg/x64_dbg.cpp, src/gui/Src/Bridge/Bridge.cpp, src/gui/Src/Bridge/Bridge.h, src/gui/Src/Gui/CPUSideBar.cpp, src/gui/Src/Gui/CPUSideBar.h, src/gui/Src/Gui/LogView.cpp, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h
Let plugins spam the user's favourites menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/895)
=> More functions for plugin

src/dbg/instruction.cpp
caught when documenting this command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/896)
=> fix app crash

src/gui/Src/Gui/AppearanceDialog.cpp, src/gui/Src/Gui/CPUSideBar.cpp, src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/CPUStack.h, src/gui/Src/Utils/Configuration.cpp, src/gui/Src/Utils/StringUtil.cpp, src/gui/Src/Utils/StringUtil.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/892)
=> stack frame lines similar to the ones in ollydbg

src/dbg/_exports.cpp, src/dbg/_plugins.cpp, src/dbg/debugger.cpp, src/dbg/debugger_commands.cpp, src/dbg/thread.cpp, src/dbg/thread.h, src/gui/Src/Gui/AppearanceDialog.cpp, src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/CPUStack.h, src/gui/Src/Gui/RegistersView.cpp, src/gui/Src/Gui/RegistersView.h, src/gui/Src/Utils/Configuration.cpp
* push and pop actions
* merge pause actions into a single routine
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/902)
=> push and pop actions

src/gui/Src/Gui/MainWindow.cpp
fix issue #915
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/916)
=> fix issue #915

src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/919)
=> simplify code

.gitignore, src/dbg/jit.h, src/dbg/taskthread.h
Minor fixes to jit.h and taskthread.h, as well as an additional entry to .gitignore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/977)
=> Minor fixes

src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/CPUStack.h
Align stack pointer when it is not aligned to word size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/987)
=> Realign stack pointer

src/gui/Src/Gui/CPUStack.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/984)
=> Fix for Follow in Dump N in Stack View

src/dbg/expressionfunctions.cpp, src/dbg/exprfunc.cpp, src/dbg/exprfunc.h, src/gui/Src/BasicView/Disassembly.cpp, src/gui/Src/Disassembler/QBeaEngine.cpp, src/gui/Src/Disassembler/capstone_gui.cpp, src/gui/Src/Disassembler/capstone_gui.h
#971
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/993)
=> fix issue 971 and add thread id function

src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/BasicView/AbstractTableView.h, src/gui/Src/BasicView/Disassembly.cpp, src/gui/Src/BasicView/HexDump.cpp, src/gui/Src/Gui/CPUArgumentWidget.cpp, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/CPUDump.h, src/gui/Src/Gui/FavouriteTools.cpp, src/gui/Src/Gui/LineEditDialog.cpp, src/gui/Src/Gui/LineEditDialog.h, src/gui/Src/Gui/LogView.cpp, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/RegistersView.cpp, src/gui/Src/Gui/WatchView.cpp, src/gui/Src/Utils/MiscUtil.cpp, src/gui/Src/Utils/MiscUtil.h, src/gui/x64dbg.pro
*  Forward and Backward mouse buttons found in some models of mice.
*  No confirmation when adding functions.
*  Allocate memory from the dump menu.
*  Placeholder tips for learners.
*  disable/cancel log redirect (issue #939)
*  use windows config singe step size (issue #1000)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1004)
=> GUI improvements

src/dbg/debugger.cpp, src/dbg/thread.cpp, src/dbg/thread.h, src/gui/Src/BasicView/StdTable.cpp, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h, src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/FavouriteTools.cpp, src/gui/Src/Gui/FavouriteTools.h, src/gui/Src/Gui/FavouriteTools.ui, src/gui/Src/Gui/LogView.cpp, src/gui/Src/Gui/RegistersView.cpp, src/gui/Src/Gui/ShortcutsDialog.cpp, src/gui/Src/Gui/ShortcutsDialog.h, src/gui/Src/Gui/ShortcutsDialog.ui, src/gui/Src/Gui/SymbolView.cpp, src/gui/Src/Utils/Configuration.cpp
*   Add auto-scrolling to tables
*   Add clear shortcut button
*   Add more shortcuts
*   Add menu entry for new thread
*   Display user-friendly name of the thread
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1035)
=> Add auto-scrolling to tables etc

src/dbg/debugger_commands.cpp, src/dbg/instruction.cpp, src/gui/Src/Gui/CPUSideBar.cpp, src/gui/Src/Gui/CPUSideBar.h, src/gui/Src/Gui/MemoryMapView.cpp, src/gui/Src/Gui/SettingsDialog.cpp, src/gui/Src/Gui/SettingsDialog.h, src/gui/Src/Gui/SettingsDialog.ui, src/gui/Src/Utils/Configuration.cpp
Now the user can define custom labels in sidebar by watching it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1040)
=> Add Watch Items to Labels in Sidebar

src/gui/Src/Gui/CPUWidget.cpp, src/gui/Src/Gui/RegistersView.cpp, src/gui/Src/Gui/RegistersView.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1046)
=> Add Follow in Dump N menu to the Registers view

src/gui/Src/Gui/BreakpointsView.cpp, src/gui/Src/Gui/BreakpointsView.h, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Utils/Configuration.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1049)
=> Shortcuts for animation

src/dbg/expressionfunctions.cpp, src/dbg/exprfunc.cpp, src/dbg/exprfunc.h, src/dbg/instruction.cpp, src/dbg/instruction.h, src/dbg/x64_dbg.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1050)
=> GetTickCount

src/gui/Src/BasicView/StdTable.cpp, src/gui/Src/Gui/MemoryMapView.cpp, src/gui/Src/Gui/ScriptView.cpp, src/gui/Src/Gui/ScriptView.h, src/gui/Src/Gui/WatchView.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1057)
=> more icons

src/gui/Src/Gui/HexEditDialog.cpp, src/gui/Src/Gui/HexEditDialog.h, src/gui/Src/Gui/HexEditDialog.ui, src/gui/Src/Gui/HexLineEdit.cpp, src/gui/Src/Gui/HexLineEdit.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1062)
=> codepage hex editor

src/dbg/debugger.cpp
Now the user can use "run" commands in initialization script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1063)
=> asynchronize initialization script

src/gui/Src/Gui/LogView.cpp, src/gui/Src/Gui/LogView.h
Addresses will become clickable hyperlinks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1070)
=> hyperlink in log

src/gui/Src/BasicView/LabeledSplitter.cpp, src/gui/Src/BasicView/LabeledSplitter.h, src/gui/Src/BasicView/LabeledSplitterDetachedWindow.cpp, src/gui/Src/BasicView/LabeledSplitterDetachedWindow.h, src/gui/x64dbg.pro
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1077)
=> Detachable breakpoint view

src/dbg/filehelper.cpp, src/gui/Src/Gui/ScriptView.cpp, src/gui/Src/Gui/ScriptView.h
Now we don't need to create or edit a text file to execute a script. Just paste it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1078)
=> paste script from clipboard

src/dbg/filehelper.cpp, src/gui/Src/BasicView/LabeledSplitter.cpp, src/gui/Src/BasicView/LabeledSplitter.h, src/gui/Src/BasicView/LabeledSplitterDetachedWindow.h, src/gui/Src/BasicView/StdTable.cpp, src/gui/Src/Gui/BreakpointsView.cpp, src/gui/Src/Gui/DataCopyDialog.cpp, src/gui/Src/Gui/DataCopyDialog.h, src/gui/Src/Gui/DisassemblerGraphView.cpp, src/gui/Src/Gui/LogView.cpp, src/gui/Src/Gui/LogView.h, src/gui/Src/Gui/ScriptView.cpp
*  fixed crash when detaching
*  more icons for copy menu
*  changed pseudo url for clipboard
*  add ip address to data copy
*  auto scroll for log
*  reordered breakpoints
*  display 3 tables for breakpoints per default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1079)
=> improvements

src/gui/Src/BasicView/StdTable.cpp, src/gui/Src/BasicView/StdTable.h, src/gui/Src/Gui/LogView.cpp, src/gui/Src/Gui/LogView.h, src/gui/Src/Gui/MemoryMapView.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1105)
=> Copy Table To Log, Copy Log To Notes

src/gui/Src/Gui/FavouriteTools.cpp, src/gui/Src/Gui/FavouriteTools.h, src/gui/Src/Gui/LogView.cpp, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Utils/Configuration.cpp
*   Fix enable of buttons in favourite tools dialog
*   shortcut for blog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1106)
=> Fix enable of buttons in favourite tools dialog

src/gui/Src/Gui/EditFloatRegister.cpp
fix issue #1127
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1130)
=> fix issue 1127

src/gui/Src/BasicView/Disassembly.cpp, src/gui/Src/BasicView/HexDump.cpp, src/gui/Src/BasicView/ReferenceView.cpp, src/gui/Src/Gui/BreakpointsView.cpp, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/EditFloatRegister.cpp, src/gui/Src/Utils/StringUtil.h
use a faster converter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1133)
=> small performance improvements

src/dbg/assemble.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1134)
=> Keystone: for short jumps, reject commands larger than 2 bytes

src/dbg/commands/cmd-user-database.cpp
Closes #1088
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1136)
=> Add Label/Comment column to Bookmark list

src/dbg/commands/cmd-variables.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1138)
=> use reference view for varlist

src/dbg/commands/cmd-analysis.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1137)
=> use RIP as default parameter for "imageinfo"

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/CallStackView.cpp, src/gui/Src/Gui/CustomizeMenuDialog.cpp, src/gui/Src/Gui/CustomizeMenuDialog.h, src/gui/Src/Gui/CustomizeMenuDialog.ui, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h, src/gui/Src/Gui/MainWindow.ui, src/gui/Src/Gui/ThreadView.cpp, src/gui/Src/Gui/WatchView.cpp, src/gui/Src/Utils/Configuration.cpp, src/gui/Src/Utils/Configuration.h, src/gui/Src/Utils/MenuBuilder.cpp, src/gui/Src/Utils/MenuBuilder.h, src/gui/x64dbg.pro, src/x64dbg_translations.pro
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1144)
=> Hide some menus in a submenu

src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h, src/gui/Src/Gui/MainWindow.ui, src/gui/Src/Gui/TabWidget.cpp, src/gui/Src/Gui/TabWidget.h, src/gui/Src/Utils/Configuration.cpp
* This action will close the current tab and open the tab to the right of the closed one.
* Default hotkey is Ctrl+W.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1153)
=> GUI: Add hide tab action

src/dbg/commands/cmd-searching.cpp, src/dbg/commands/cmd-searching.h, src/dbg/reference.cpp, src/dbg/x64dbg.cpp, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h, src/gui/Src/Gui/CustomizeMenuDialog.cpp, src/gui/Src/Gui/CustomizeMenuDialog.h, src/gui/Src/Gui/CustomizeMenuDialog.ui, src/gui/Src/Utils/MenuBuilder.cpp
*   search for references to GUID, including ASCII string, Unicode string and binary form of GUID
*   disselect all hidden menus
*   use both "cfanal" and "analx" for Ctrl+A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1156)
=> search for GUID

src/gui/Src/Gui/CPUStack.cpp
Closes #1103.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1158)
=> CPUStack: User can now select a different address after freezing the stack.

src/gui/Src/Gui/DataCopyDialog.cpp, src/gui/Src/Gui/DataCopyDialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1172)
=> copy in base64

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h
Closes #1096.
The gif is kinda shitty this time but have it anyways :P 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1177)
=> Added copy selection to file options for CPUDisassembly.

.gitignore, src/dbg/commands/cmd-searching.cpp, src/gui/Src/Gui/MainWindow.cpp
I know x64dbg is meant to be compiled with VS2013, but it's only a few 'const's away from compiling in VS2015 too ;)
Also added a new annoying file type to gitignore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1194)
=> VS2015 fixes

src/gui/Src/Gui/WatchView.cpp, src/gui/Src/Gui/WatchView.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1197)
=> modify value of watch item

src/gui/Src/Gui/MainWindow.cpp
fixes #1169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1199)
=> GUI: run until selection in graph view

src/gui/Src/Gui/DisassemblerGraphView.cpp, src/gui/Src/Gui/DisassemblerGraphView.h, src/gui/Src/Utils/Configuration.cpp
fixes #918 
also fixes bug with bottom and right border which was not drawn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1198)
=> GUI: save graph to file

src/dbg/command.cpp, src/dbg/commands/cmd-analysis.cpp, src/dbg/commands/cmd-breakpoint-control.cpp, src/dbg/commands/cmd-conditional-breakpoint-control.cpp, src/dbg/commands/cmd-debug-control.cpp, src/dbg/commands/cmd-general-purpose.cpp, src/dbg/commands/cmd-misc.cpp, src/dbg/commands/cmd-searching.cpp, src/dbg/commands/cmd-undocumented.cpp, src/dbg/commands/cmd-user-database.cpp, src/dbg/commands/cmd-variables.cpp, src/dbg/datainst_helper.cpp, src/dbg/plugin_loader.cpp, src/dbg/value.cpp
Title. I went through each file in the debugger-only code and checked ~~all~~most strings.
I'm not sure if you want to merge it immediately as it will break a bunch of translations. However, it will only get more problematic the longer it goes unchanged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1215)
=> DBG: Capitalize console error/output messages

src/gui/Src/Gui/DisassemblerGraphView.cpp, src/gui/Src/Utils/Configuration.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1222)
=> GUI: fixed inconsistent shortcuts in graph view

src/gui/Src/Gui/MemoryMapView.cpp, src/gui/Src/Utils/Configuration.cpp
"Content" of the section in "Memory Map"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1224)
=> GUI: fixed issue #1212

src/gui/Src/Gui/MemoryMapView.cpp, src/x64dbg_translations.pro
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1228)
=> fixed translation

src/gui/Src/Gui/DisassemblerGraphView.cpp, src/gui/Src/Gui/DisassemblerGraphView.h, src/gui/Src/Utils/Configuration.cpp
fixes #1174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1229)
=> GUI: Comments and labels in graph view

src/gui/Src/BasicView/Disassembly.cpp
Code folding does not work now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1233)
=> Revert "GUI: speed improvements in Disassembly"

src/bridge/bridgemain.cpp, src/bridge/bridgemain.h, src/dbg/_exports.cpp, src/dbg/_global.cpp, src/dbg/_global.h, src/dbg/debugger.cpp, src/dbg/module.cpp, src/dbg/stackinfo.cpp, src/dbg/x64dbg.cpp, src/gui/Src/Gui/RegistersView.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1243)
=> decode function offset in stack

src/gui/Src/Gui/CustomizeMenuDialog.cpp, src/gui/Src/Gui/XrefBrowseDialog.cpp, src/gui/Src/Gui/XrefBrowseDialog.h, src/gui/Src/Utils/Configuration.cpp
Set breakpoints for all xrefs or copy them
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1244)
=> context menu in xrefs dialog

src/launcher/x64dbg_launcher.cpp
#307 issue solved
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1246)
=> icon for database files

src/gui/Src/Gui/SettingsDialog.cpp, src/gui/Src/Gui/SettingsDialog.h, src/gui/Src/Gui/SettingsDialog.ui
It has been a hidden setting for a long time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1274)
=> HardcoreThreadSwitchWarning

src/gui/Src/Gui/MemoryMapView.cpp, src/gui/Src/Gui/MemoryMapView.h
The comment will be shown in the "Content" column of the memory view. It is also shown at the base address in the disassembly view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1275)
=> Comment on memory map

src/gui/Src/BasicView/LabeledSplitter.cpp, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/DisassemblerGraphView.cpp, src/gui/Src/Gui/EditBreakpointDialog.ui, src/gui/Src/Gui/RegistersView.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1306)
=> max length for breakpoint condition

src/dbg/commands/cmd-user-database.cpp, src/dbg/debugger.cpp, src/dbg/debugger.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1352)
=> Remove breakpoints from module when calling DbClear, resolves #1310

src/gui/Src/Gui/SymbolView.cpp
fixes #1329 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1357)
=> look at the symbol log font #1329

src/gui/Src/Gui/BreakpointsView.cpp, src/gui/Src/Gui/BreakpointsView.h, src/gui/Src/Gui/BreakpointsViewTable.cpp, src/gui/Src/Gui/BreakpointsViewTable.h, src/gui/x64dbg.pro, src/x64dbg_translations.pro
This closes the issue #911
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1359)
=> Showing in breakpoints tab if EIP is on a bpx

src/gui/Src/Gui/CPUDisassembly.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1365)
=> Fix "Alt+;" on operand 00000001 can use this invisible command

src/gui/Src/Gui/TabWidget.cpp
fixes #1327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1375)
=> removed code which set the active window to the closed tab

src/gui/Src/Gui/AppearanceDialog.cpp, src/gui/Src/Gui/LogView.cpp, src/gui/Src/Utils/Configuration.cpp
an option edit(chang) the color（log windows） (#1386)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1387)
=> an option edit(chang) the color（log windows） (#1386)

src/gui/Src/Bridge/Bridge.cpp, src/gui/Src/Bridge/Bridge.h, src/gui/Src/Gui/AppearanceDialog.cpp, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h, src/gui/Src/Gui/LogView.cpp, src/gui/Src/Utils/Configuration.cpp, src/gui/Src/Utils/RichTextPainter.cpp, src/gui/Src/Utils/RichTextPainter.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1394)
=> copy rich text

src/gui/Src/Gui/CPUDisassembly.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1402)
=> vulunability

src/dbg/debugger.cpp, src/dbg/memory.cpp, src/dbg/memory.h
fixes  #489 when launching a process from x64dbg.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1412)
=> Remote process cookie support for Windows XP/Vista/7

src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/Gui/ColumnReorderDialog.cpp
fixes #1308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1421)
=> Fixed random behavior when hiding / showing / reordering StdTable columns

src/dbg/memory.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1426)
=> fix MemRead to only return true if NumberOfBytesRead is equal to the requested read size

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h
closes #1420
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1441)
=> added pattern option to "search for -> all modules" menu in disassembly view

src/gui/Src/Disassembler/capstone_gui.cpp
closes #1332
preview:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1440)
=> treat fs / gs usage as unusual

src/dbg/_dbgfunctions.cpp, src/dbg/_dbgfunctions.h, src/dbg/debugger.cpp, src/dbg/handles.cpp, src/dbg/handles.h, src/gui/Src/Gui/CallStackView.cpp, src/gui/Src/Gui/HandlesView.cpp, src/gui/Src/Gui/HandlesView.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1417)
=> handles and windows view

src/dbg/symbolinfo.cpp
Attempt to load symbols from .pdb path embedded in the PE executable prior to executing any network IO. Currently the order is the opposite. See #1502.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1504)
=> DBG: load symbols from local filesystem first (#1502)

src/gui/Src/Gui/CPUDump.cpp
This pull request enables the user to explicitly specify the data type for a piece of data and the tooltip in the dump will respect it. Currently, the user can only follow the data in disassembly in order to specify the data type even if it is not a piece of code. We can enable the user to specify encoding type in the dump in future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1518)
=> Respect encoding type for tooltips in dump

src/gui/Src/Gui/CPUArgumentWidget.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1519)
=> __fastcall enabled

src/dbg/animate.cpp, src/dbg/commands/cmd-undocumented.cpp, src/dbg/commands/cmd-undocumented.h, src/dbg/taskthread.h, src/dbg/value.cpp, src/dbg/x64dbg.cpp, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/RegistersView.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1529)
=> Improved user experience on single-core CPU

src/gui/Src/Gui/RegistersView.cpp
Problem fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1532)
=> fixed #1467

src/dbg/commands/cmd-memory-operations.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1536)
=> internationalization issue fixed

src/gui/Src/Utils/StringUtil.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1552)
=> Fixed "Arp" (April) to "Apr"

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUMultiDump.cpp, src/gui/Src/Gui/CPUMultiDump.h, src/gui/Src/Gui/LocalVarsView.cpp, src/gui/Src/Gui/LocalVarsView.h, src/gui/Src/Utils/Configuration.cpp, src/gui/x64dbg.pro, src/x64dbg_translations.pro
A more appropriate icon is needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1555)
=> Local variables view

src/dbg/value.cpp
fixes #1027
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1556)
=> added string prefix

src/gui/Src/Disassembler/capstone_gui.cpp, src/gui/Src/Disassembler/capstone_gui.h, src/gui/Src/Gui/SettingsDialog.cpp, src/gui/Src/Gui/SettingsDialog.h, src/gui/Src/Gui/SettingsDialog.ui, src/gui/Src/Utils/Configuration.cpp
fixes #614
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1557)
=> 0x prefix for values

src/gui/Src/Gui/CPUMultiDump.cpp, src/gui/Src/Gui/LocalVarsView.cpp, src/gui/Src/Gui/LocalVarsView.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1560)
=> Local variables view improved

src/dbg/commands/cmd-operating-system-control.cpp, src/dbg/commands/cmd-operating-system-control.h, src/dbg/x64dbg.cpp, src/gui/Src/Gui/HandlesView.cpp, src/gui/Src/Gui/HandlesView.h, src/gui/Src/Gui/HandlesWindowViewTable.cpp, src/gui/Src/Gui/HandlesWindowViewTable.h, src/gui/x64dbg.pro, src/x64dbg_translations.pro
- Enable/Disable window
- Follow classproc in disassembler
- Toggle bp in classproc
- Message bp in classproc (not implemented entry)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1561)
=> Actions added to Handles/Windows table

src/gui/Src/Gui/CalculatorDialog.cpp, src/gui/Src/Gui/CalculatorDialog.h, src/gui/Src/Gui/CalculatorDialog.ui
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1569)
=> fixed 1278

src/gui/Src/Gui/MessagesBreakpoints.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1577)
=> Select "WM_COMMAND" per default

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h, src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/CPUDump.h, src/gui/Src/Gui/CPUInfoBox.cpp, src/gui/Src/Gui/CPUInfoBox.h, src/gui/Src/Gui/CPUWidget.cpp, src/gui/Src/Gui/CPUWidget.h, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h, src/gui/Src/Utils/Configuration.cpp
- Added quick instruction references view in cpu extra info widget
- Added menu entry to modify memory values in cpu extra info widget
- Added menu entry to show current instruction references from cpu extra
info widget
- Added menu entry to copy file offset in disassembly and dump widget
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1583)
=> Some minor cpu info box enhancements

src/gui/Src/Gui/CPUSideBar.cpp, src/gui/Src/Utils/Breakpoints.cpp, src/gui/Src/Utils/Breakpoints.h
I don't wanna lose data for my conditional breakpoints when clicking on the side bar again. The user now can only use left mouse button to toggle breakpoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1584)
=> Don't lose data when clicking side bar

src/gui/Src/Gui/AssembleDialog.cpp, src/gui/Src/Gui/AttachDialog.cpp, src/gui/Src/Gui/EditBreakpointDialog.cpp, src/gui/Src/Gui/GotoDialog.cpp, src/gui/Src/Utils/Configuration.cpp, src/gui/Src/Utils/Configuration.h
It can remember the window position of dialogs with a simple to use utility function. This feature should be promoted to every dialog. But it is very late now. So I will push it now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1586)
=> remembers dialog position

src/gui/Src/Gui/SymbolView.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1605)
=> Defense against malicious "explorer.exe"

src/gui/Src/Gui/HandlesView.cpp
Closes #1597
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1602)
=> Fixes handles search tables not updating properly

src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/BasicView/AbstractTableView.h, src/gui/Src/BasicView/SearchListView.cpp, src/gui/Src/BasicView/SearchListView.h, src/gui/Src/Gui/HandlesView.cpp, src/gui/Src/Gui/SymbolView.cpp
Fixed wrong behavior when using search lists and changing layouts between mList and mSearchList
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1606)
=> Fixed wrong behavior on search lists

src/dbg/debugger.cpp, src/dbg/debugger.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1612)
=> Fixes #1608

src/gui/Src/Gui/BrowseDialog.cpp, src/gui/Src/Gui/DataCopyDialog.cpp, src/gui/Src/Gui/EntropyDialog.cpp, src/gui/Src/Gui/FavouriteTools.cpp, src/gui/Src/Gui/HexEditDialog.cpp, src/gui/Src/Gui/MemoryMapView.cpp, src/gui/Src/Gui/PatchDialog.cpp, src/gui/Src/Gui/SettingsDialog.cpp, src/gui/Src/Gui/SimpleTraceDialog.cpp, src/gui/Src/Gui/WordEditDialog.cpp, src/gui/Src/Utils/Configuration.cpp, src/gui/Src/Utils/MiscUtil.cpp, src/gui/Src/Utils/MiscUtil.h, src/gui/Src/Utils/UpdateChecker.cpp
Changing screen resolution from high resolution to low resolution will not hide windows; Clean up message boxes a bit.
=> don't restore window pos invisible; clean up msgbox

src/dbg/commandline.cpp, src/dbg/commands/cmd-searching.cpp, src/dbg/debugger.cpp
Fixed some small unsafe codes with the aid of static code analyzers.
=> Fixed some unsafe code

src/gui/Src/Gui/AssembleDialog.cpp, src/gui/Src/Gui/AssembleDialog.h, src/gui/Src/Utils/ValidateExpressionThread.cpp, src/gui/Src/Utils/ValidateExpressionThread.h
Loving your project, keep up the good work!
=> GUI: revalidate when toggling 'Keep Size' in AssembleDialog

src/dbg/commands/cmd-tracing.cpp, src/dbg/debugger.cpp
=> can use rtu

src/gui/Src/Gui/LineEditDialog.cpp, src/gui/Src/Gui/LineEditDialog.h, src/gui/Src/Gui/RegistersView.cpp
You can enter floating point numbers in the edit box. Hex numbers are also accepted. You must enter decimal point for floating point number, otherwise it is treated as a hex number.
=> can enter floating point number

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h
=> GUI: download symbols in CPU tab

src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/RegistersView.cpp, src/gui/Src/Gui/RegistersView.h
Small fixes and deletion of unnecessary stuff
Found with cppcheck 1.80
=> Small fixes an deletion of unnecessary stuff

src/dbg/value.cpp
=> Fixes #1699 Arch-Indep-Registers

src/dbg/analysis/recursiveanalysis.cpp, src/gui/Src/BasicView/HexDump.cpp, src/gui/Src/BasicView/HexDump.h, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/CPUDump.h, src/gui/Src/Gui/CPUMultiDump.cpp, src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/CPUStack.h, src/gui/Src/Gui/DisassemblerGraphView.cpp, src/gui/Src/Gui/DisassemblerGraphView.h, src/gui/Src/Utils/VaHistory.h, src/gui/x64dbg.pro
=> graph for switch statements

src/gui/Src/Gui/CPUInfoBox.cpp
=> Show address with label in InfoBox

src/dbg/msgqueue.cpp
How can you check `Stack->Destroy` if it is deleted?
=> Properly exit x64dbg

src/gui/Src/Gui/SettingsDialog.cpp, src/gui/Src/Gui/SettingsDialog.h, src/gui/Src/Gui/SettingsDialog.ui
Closes #1396.  
Nothing interesting to see here.
=> Added setting that controls MaxModuleSize.

src/gui/Src/Gui/DataCopyDialog.cpp, src/gui/Src/Gui/DataCopyDialog.h
#975 turned out to be built-in feature of Qt 5.6. Also refactored DataCopyDialog slightly.
=> Copy cryptographic hash

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Utils/Configuration.cpp
=> GUI: add shortcuts for search in current module

src/dbg/commands/cmd-undocumented.cpp, src/gui/Src/Disassembler/capstone_gui.cpp
=> Fixes for #1797

src/dbg/commands/cmd-analysis.cpp, src/dbg/expressionfunctions.cpp, src/dbg/exprfunc.cpp, src/dbg/exprfunc.h, src/dbg/formatfunctions.cpp, src/dbg/mnemonichelp.cpp, src/dbg/mnemonichelp.h, src/dbg/x64dbg.cpp, src/gui/Src/Gui/CPUInfoBox.cpp, src/gui/Src/Gui/CPUInfoBox.h, src/gui/Src/Gui/DataCopyDialog.cpp, src/gui/Src/Gui/DataCopyDialog.ui, src/gui/Src/Gui/LocalVarsView.cpp, src/gui/Src/Utils/MiscUtil.cpp, src/gui/Src/Utils/MiscUtil.h
NTSTATUS format function is not used in register view currently because C0000005 message is bad.
=> Multiple enhancements

src/gui/Src/Gui/DataCopyDialog.cpp, src/gui/Src/Gui/DataCopyDialog.h
=> View and copy raw string

src/dbg/handles.cpp
#1961. Tested on Windows XP. It doesn't show process name yet because it is somewhat more expensive.
=> show PID or TID in handles view

src/dbg/WinInet-Downloader/downslib.cpp
The VS2017 15.8 update updated the MS DIA SDK and added a bunch of new internal functions for a `PortablePDB` class, including `PortablePDB::ConvertPortablePDB()` which is called by `IDiaDataSource::loadDataFromIStream()`. I don't know what it's for, but hopefully this means that `/DEBUG:FASTLINK` PDBs are going to give more useful output.
Unfortunately there are two problems:
- `msdia140.dll` is sloppy and doesn't do basic validation like checking whether a PDB has a 0 file size.
- x64dbg is sloppy and creates 0 file size PDBs. (e.g. if the symbol server returned 404)
This means x64dbg will randomly crash on **some** apps: namely if the PDB of the app or a DLL used by it was previously queried unsuccessfully.
This PR expands the cleanup lambda in `downslib_download` to delete the file if …
=> Delete failed PDB downloads

src/gui/Src/Gui/RegistersView.cpp, src/gui/Src/Gui/RegistersView.h
Hello all,
This PR tries to support #1972.
I 'm a fan of `x64dbg` but still not familiar with its code base yet. Many thanks for any comment.
=> Support copy individual x87 registers

src/gui/Src/Tracer/TraceBrowser.cpp, src/gui/Src/Tracer/TraceBrowser.h
=> opcode grouping in trace view

src/gui/Src/Gui/PatchDialog.cpp
=> Fix filename bug in patch menu

src/gui/Src/Gui/DisassemblerGraphView.cpp
https://github.com/x64dbg/x64dbg/issues/2128
=> zoom overview fix

src/dbg/patternfind.h, src/zydis_wrapper/zydis_wrapper.h
=> Fix compilation in VS2019

src/dbg/thread.cpp
Due to a bug in the kernel, threads that are at a suspend count of `MAXIMUM_SUSPEND_COUNT` (= 127) will have their previous suspend count value reported as 0 by `NtSuspendThread`, and thus also x64dbg since it uses suspend/resume to get the count.
On Windows >= 8.1 there is a better way to get the suspend count without suspending and resuming the thread, so I've added that as well. If this method fails the old one is used.
=> Fix ThreadGetSuspendCount if the suspend count limit is reached

src/gui/Src/Gui/CPUInfoBox.cpp, src/gui/Src/Gui/CPUInfoBox.h, src/gui/Src/Gui/ShortcutsDialog.cpp, src/gui/Src/Gui/ShortcutsDialog.h, src/gui/Src/Gui/ShortcutsDialog.ui, src/gui/Src/Utils/Configuration.cpp
I picked issue #2110 and added a small filter box in the shortcuts dialog to improve usability.
It's my first pull request here and im not familiar with QT tell me if anything is wrong!
Also arent we leaking memory by never deallocationg those QAction* in cpuInfoBox?
=> Added Shortcut for copyline and filter box in shortcut dialog

src/dbg/patternfind.cpp
=> DBG: reject wildcard only patterns

src/gui/Src/Gui/LogView.cpp, src/gui/Src/Gui/LogView.h
Fixed GUI issues discussed in #2241
=> Enhanced LogView performance

src/gui/Src/Disassembler/ZydisTokenizer.cpp, src/gui/Src/Disassembler/ZydisTokenizer.h, src/gui/Src/Tracer/TraceBrowser.cpp, src/gui/Src/Tracer/TraceBrowser.h
Hello 
Added registers and memory columns to Trace tab. I done this just for my personal use since context menu with the same data not always handy.
What is done: 
- visualisation of updated registers and values 
- visualisation of memory and updated values 
- highlight 
- copy 
- might broke something, don't know yet:)
Will appreciate any feedback to this PR.
=> more useful data in trace browser 

src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/BasicView/AbstractTableView.h, src/gui/Src/BasicView/Disassembly.cpp, src/gui/Src/BasicView/Disassembly.h, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/SettingsDialog.cpp, src/gui/Src/Gui/SettingsDialog.h, src/gui/Src/Gui/SettingsDialog.ui, src/gui/Src/Utils/Configuration.cpp, src/gui/Src/Utils/Configuration.h
=> GUI: Added option to enable/disable branch disassembly popup.

src/gui/Src/Utils/Configuration.cpp
Like OllyDbg has, very convenient
=> Set default hotkey for "Set Conditional Breakpoint"

src/dbg/breakpoint.cpp
DLL breakpoints can now be enabled/disabled/removed!
=> DBG: Fixed DLL breakpoints.

src/gui/Src/Gui/BreakpointsView.cpp, src/gui/Src/Utils/Configuration.cpp
Hopefully fix https://github.com/x64dbg/x64dbg/pull/2370
=> Maybe fix: Set default hotkey for "Set Conditional Breakpoint"

src/gui/Src/Utils/Configuration.cpp
=> Maybe fix this time: Set default hotkey for "Set Conditional Breakpoint"

src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/BasicView/AbstractTableView.h, src/gui/Src/Tracer/TraceBrowser.cpp
Do you want a small delay for appearance of disassembly popup?
=> Set a small delay for appearance of disassembly popup

src/gui/Src/BasicView/AbstractStdTable.cpp, src/gui/Src/BasicView/AbstractStdTable.h, src/gui/Src/Gui/CPUStack.cpp, src/gui/Src/Gui/DisassemblerGraphView.cpp, src/gui/Src/Gui/SymbolView.cpp, src/gui/Src/Utils/Configuration.cpp
=> Added Ctrl+C for copy line

src/gui/Src/BasicView/AbstractStdTable.cpp, src/gui/Src/BasicView/AbstractStdTable.h, src/gui/Src/Tracer/TraceBrowser.cpp, src/gui/Src/Tracer/TraceBrowser.h, src/gui/Src/Utils/Configuration.cpp, src/gui/Src/Utils/MiscUtil.cpp, src/gui/Src/Utils/MiscUtil.h
=> Export table CSV

src/gui/Src/Gui/HexEditDialog.cpp, src/gui/Src/Gui/HexEditDialog.h
I did this PR based in a suggestion from this video https://www.youtube.com/watch?v=we-BGBYIUZo
=> Add python on edit data

src/dbg/disasm_helper.cpp
There was a bug when the string is long. This has been fixed and it can find 20,000+ strings in sample mentioned in #2449 including the desired string.
=> Fix string detection

src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h
=> fixed GuiShowCpu() switching graph mode

src/gui/Src/Gui/AppearanceDialog.cpp, src/gui/Src/Utils/Configuration.cpp
Config/__Appearance dialog__ changed order of entries to be more logic
* SideBarJumps forward/backward are underneath 
* SideBarBackgroundColor at the top
=> Appearance: changed order of entries in SideBar

bin/themes/Dark/style.ini, src/gui/Src/Gui/AboutDialog.ui, src/gui/Src/Gui/AppearanceDialog.cpp, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h, src/gui/Src/Utils/Configuration.cpp, src/gui/Src/main.cpp
Hi,
I noticed that the dark blue link color is not really readable with the dark theme enabled and made it changeable.
=> Link color themeable

src/gui/Src/Gui/AppearanceDialog.ui, src/gui/Src/Gui/AssembleDialog.ui, src/gui/Src/Gui/CloseDialog.cpp, src/gui/Src/Gui/CloseDialog.ui
=> Fix appearance, assemble and close dialog when using ultra large font

src/dbg/analysis/recursiveanalysis.cpp, src/dbg/commands/cmd-gui.cpp, src/dbg/memory.cpp, src/gui/Src/Gui/SettingsDialog.ui
Allow animation interval greater than 100ms
Don't remove Xref when pressing "A"
=> Allow animation interval greater than 100ms

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CalculatorDialog.ui, src/gui/Src/Gui/ComboBoxDialog.ui, src/gui/Src/Gui/ExceptionRangeDialog.ui, src/gui/Src/Gui/MessagesBreakpoints.ui, src/gui/Src/Gui/PageMemoryRights.cpp, src/gui/Src/Gui/PatchDialog.cpp, src/gui/Src/Gui/PatchDialog.ui, src/gui/Src/Gui/SystemBreakpointScriptDialog.ui, src/gui/Src/Gui/WordEditDialog.ui, src/gui/Src/main.cpp, src/gui/Src/main.h
Dialogs now use a layout and some dialogs can be resized so they don't look too small on big monitors.
=> Fixed more windows when using ultra large font

src/dbg/commands/cmd-user-database.cpp, src/dbg/database.cpp, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.ui, src/gui/Src/Utils/Configuration.cpp
4 more database actions in file menu.
=> Database actions in the file menu, and recover database backup

src/launcher/x64dbg_launcher.cpp
=> LAUNCHER: fix typo in x64dbg_launcher.cpp

src/gui/Src/Gui/CPUWidget.cpp, src/gui/Src/Gui/RegistersView.cpp, src/gui/Src/Gui/RegistersView.h, src/gui/Src/Tracer/TraceRegisters.cpp, src/gui/Src/Tracer/TraceRegisters.h, src/gui/Src/Tracer/TraceWidget.cpp
=> Allow registers to be resized smaller & use default scrollbar style

src/gui/Src/Disassembler/ZydisTokenizer.cpp
=> Correct mask register display for "vaddps zmm1{k2},zmm2,zmm3"

src/gui/Src/Tracer/TraceBrowser.cpp
=> Fix typo in TraceBrowser.cpp

src/dbg/commands/cmd-plugins.cpp, src/dbg/debugger.cpp, src/dbg/debugger_tracing.h
=> Break when there is an error in conditional breakpoint or tracing

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Tracer/TraceBrowser.cpp, src/gui/Src/Utils/RichTextPainter.cpp, src/gui/Src/Utils/RichTextPainter.h
=> don't copy html if more than 2048 lines are selected

src/gui/Src/BasicView/HexDump.cpp
My fault, sorry for duplication of work.
see: 
https://github.com/x64dbg/x64dbg/pull/2790#pullrequestreview-810733354
=> Fix #2790 mistake

src/dbg/_exports.cpp, src/gui/Src/Gui/BreakpointsView.cpp
There's something useful in conditional breakpoint, the user shouldn't have to copy them to comments.
=> Add autocomment for conditional breakpoint

src/gui/Src/Gui/BreakpointsView.cpp, src/gui/Src/Gui/BreakpointsView.h
It works, but I don't have more time to polish it right now.
=> copy and paste breakpoint conditions

src/dbg/stringformat.cpp
Now only ST(...) is missing (ldconvert required)
=> Add support for printing floating point numbers in XMM/YMM

src/gui/Src/Gui/LogView.cpp, src/gui/Src/Gui/LogView.h
To increase flexibility for user to search for a pattern
inside the log instead of copying to some other tool.
=> Adding search action in LogView

README_zh-CN.md
Translated from the readme.md file
Closes #2841
=> Add readme Simplified Chinese document

src/gui/Src/Gui/HandlesView.cpp, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/MainWindow.h
=> Add detach and exit to exit dialog

src/dbg/commands/cmd-searching.cpp, src/dbg/commands/cmd-searching.h, src/dbg/reference.cpp, src/dbg/reference.h, src/dbg/x64dbg.cpp, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h
[#2786](https://github.com/x64dbg/x64dbg/issues/2786)
[#1461](https://github.com/x64dbg/x64dbg/issues/1461)
[#2334](https://github.com/x64dbg/x64dbg/issues/2334)
=> Add "All User Modules","All System Modules" To RMB

src/dbg/exhandlerinfo.cpp, src/dbg/exhandlerinfo.h
Closes https://github.com/x64dbg/x64dbg/issues/2898
=> Using build number instead of magic number

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Utils/Configuration.cpp
=> Find strings in current module

src/bridge/bridgemain.cpp
Remove szIniFile message box in launcher
=> Remove debug code in launcher

src/bridge/bridgemain.cpp
The "RtlGetVersion" function lacks calling convention "WINAPI", causes a crash on Windows 7.
=> Fix crash on Windows 7

src/gui/Src/BasicView/StdIconTable.h, src/gui/Src/Gui/CallStackView.cpp, src/gui/Src/Gui/CallStackView.h, src/gui/Src/Gui/MemoryMapView.cpp, src/gui/Src/Gui/MemoryMapView.h, src/gui/Src/Gui/SymbolView.cpp, src/gui/Src/Gui/SymbolView.h
Call stack, memory map and symbols view now get a party column
=> Use an icon to represent user/system party to reduce column width

src/gui/Src/Tracer/TraceBrowser.cpp
simpler https://github.com/x64dbg/x64dbg/pull/2952/files, just stealing the appveoyr build for myself locally
=> addRegValues eflags

src/dbg/module.cpp
=> Use section raw size if virtual size is null

src/launcher/x64dbg_launcher.cpp
=> Add relative path support to launcher

src/gui/Src/Gui/CallStackView.cpp, src/gui/Src/Gui/MemoryMapView.cpp, src/gui/Src/Gui/SymbolView.cpp
It's a small change but good practice :)
=> Fixed "Party" column width

src/gui/Src/Gui/CPURegistersView.cpp, src/gui/Src/Gui/CPURegistersView.h
=> Added context menu entries (Inc, dec, zero) to registers

src/dbg/thread.cpp
Closes #3016 
It gets the name in ThreadCreate and ThreadGetList, both sources work on their own separately if you comment out the other one.
The reason I added thread name updating also to ThreadGetList is that technically the app can update its thread description at any time (which docs mention), which could mean initial name could get outdated, even though such situation is rather rare. But given the threads are refreshed every 1 second, it should be fine.
For code style I mimicked how _GetThreadId is accessed in the same file.
Tested:
There's one oddity I noticed though: the thread name won't be shown in Handles view instead of the thread number, unless you explicitly set a thread name yourself in GUI, even if to the same value. Is that expected behavior?
=> Get thread name from GetThreadDescription

src/dbg/stringformat.cpp, src/dbg/variable.cpp, src/dbg/variable.h, src/gui/Src/Gui/MainWindow.h
* fixed "vardel x" said x is deleted, but x is not deleted actually.
* cleaned up XMM formatting. I wanted to allow printing XMM in hex but it seems to require more work later.
=> Misc Maintenance

src/gui/Src/Tracer/TraceFileReader.cpp
I have decided to reduce number of cached trace file pages for x32dbg, over 1GB memory usage on x32dbg is unacceptable, especially considering #3098 will consume large amount of memory as well, and that is not paged.
=> Reduce number of cached trace file pages to save memory

src/dbg/ntdll/ntdll.h, src/dbg/pdbdiafile.cpp, src/dbg/symbolinfo.cpp
This PR upstreams two small PDB handling-related changes I made while trying to get a MinGW-created PDB file to load (ultimately unsuccessfully, but at least this now gives an error message with the failure reason rather than deleting the PDB file).
For most users the most important change is probably the fact that "download symbols for all modules" should now be a lot faster if some or all of the symbol files already exist on disk. These files will still be validated, but not downloaded.
=> Symbol loading improvements

src/gui/Src/BasicView/SearchListView.cpp, src/gui/Src/Gui/CPUWidget.cpp, src/gui/Src/Gui/HandlesView.cpp, src/gui/Src/Gui/TabWidget.cpp
It should be able to announce the names for all views in screen reader now (#2234).
=> Add accessible names

src/dbg/encodemap.cpp
Fixes #3093
P.S. While debugging, I got the "Trying to get last error of a thread that doesn't exist!" assert and had to comment it out.
=> Fix a DbgSetEncodeType crash if an out-of-date db file is used

src/dbg/exprfunc.cpp, src/gui/Src/BasicView/ReferenceView.cpp, src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/ReferenceManager.cpp
Increment or decrement the highlighted reference in References tab when using Actions->Go to Next/Previous Reference
=> Update References tab highlighting

src/gui/Src/Gui/EditFloatRegister.cpp, src/gui/Src/Gui/GotoDialog.cpp, src/gui/Src/Gui/GotoDialog.h, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Tracer/TraceBrowser.cpp, src/gui/Src/Utils/ActionHelpers.h, src/gui/Src/Utils/CommonActions.cpp, src/gui/Src/Utils/CommonActions.h
* Status bar tips are added to some actions supported by CommonActions
* Allow go to while not debugging in trace view
=> Add tips to some common actions

src/gui/Src/Gui/DisassemblerGraphView.cpp, src/gui/Src/Gui/DisassemblerGraphView.h
It should be somewhere close to 100% copy of the highlighting functionality from the disassembly view. Implemented by adding another field to the "Text" structure. Now each "Text" object also carries Zydis tokens for the instruction it represents.
I refactored this structure a bit to couple those two fields (`lines` and `lineTokens`) together. Also, basic block headers, RVAs, comments, etc are not highlightable.
A few things that I may or may not have had to do:
- Removed the raw pointer field "highlight_token" (replaced with ZydisTokenizer::SingleToken).
- Removed the structures "Token" and "HighlightToken", since they are not presently used.
- Made a full copy (or I think so) of the disassembly's highlighting behaviour even though it's weird sometimes. The highlighting mode (the red …
=> Add Highlighting mode to the Graph view

src/gui/Src/Tracer/TraceBrowser.cpp
=> removed extra dot when saving trace dump

src/gui/Src/Gui/ReferenceManager.cpp, src/gui/Src/Gui/SourceViewerManager.cpp
The documentation says `removeTab` doesn't delete the widget.
=> delete widget when closing tab

src/gui/Src/Bridge/Bridge.cpp, src/gui/Src/Bridge/Bridge.h, src/gui/Src/Gui/MemoryMapView.cpp, src/gui/Src/Gui/MemoryMapView.h
=> Fix #3198: Implement GuiSelectionSet for GUI_MEMMAP

src/dbg/module.cpp
=> Fix an anti-debug trick used by GuLoader

src/gui/Src/Gui/RegistersView.cpp
=> Fix a typo

src/gui/Src/BasicView/StdIconTable.cpp, src/gui/Src/BasicView/StdIconTable.h, src/gui/Src/Gui/CallStackView.cpp, src/gui/Src/Gui/CallStackView.h
=> Auto switch thread when following callstack

src/dbg/database.cpp, src/dbg/module.cpp, src/dbg/module.h
The non-default module party set by the user is saved per #2608.
=> Save module party

src/gui/Src/Gui/CallStackView.cpp, src/gui/Src/Gui/CallStackView.h
=> Add symbol loading commands to the callstack view context menu.

src/gui/Src/Gui/DisassemblerGraphView.cpp
The new release is not yet ready for download, so another update here. Added a messagebox when the graph image failed to save.
=> Alert when image saving failed

src/dbg/TraceRecord.cpp, src/zydis_wrapper/zydis_wrapper.cpp, src/zydis_wrapper/zydis_wrapper.h
also do horrible hacks while doing that
=> Print implict memory accesses while tracing

src/gui/Src/Bridge/Bridge.cpp, src/gui/Src/Bridge/Bridge.h, src/gui/Src/Gui/MainWindow.cpp, src/gui/Src/Gui/SymbolView.cpp
Some general maintenance of plugin API
=> Allow GuiFocusView to also focus on memmap,symbols and threads

setenv.bat
Update the paths in setenv.bat to point to QMake 5.6.3 instead of 5.6.2
=> Update setenv.bat with the correct paths

src/gui/Src/Gui/CPUDisassembly.cpp, src/gui/Src/Gui/CPUDisassembly.h
Used the given plugin as a base. 
Closes #3409
=> Add option to copy selection bytes only

src/gui/Src/BasicView/AbstractTableView.cpp, src/gui/Src/BasicView/Disassembly.cpp, src/gui/Src/Gui/CPUWidget.cpp, src/gui/Src/Gui/DisassemblerGraphView.cpp, src/gui/Src/Gui/DisassemblyPopup.cpp, src/gui/Src/QHexEdit/QHexEditPrivate.cpp, src/gui/Src/Tracer/TraceWidget.cpp
It turns out just changing a setting can fix most issues. Now at least the disassembly is usable. I assume this have no performance cost.
=> Use LayoutDirectionAuto to fix RTL issues

src/dbg/breakpoint.cpp
=> Fix wrong BpToBridgeHwSize return value

src/gui/Src/Gui/LogView.cpp
=> Fix log redirection errors

src/gui/Src/BasicView/HexDump.cpp, src/gui/Src/BasicView/HexDump.h, src/gui/Src/Gui/CPUDump.cpp, src/gui/Src/Gui/CPUDump.h, src/gui/Src/Tracer/TraceDump.cpp, src/gui/Src/Tracer/TraceDump.h
Many CPUs support F16C, so there should be support for half float in x64dbg as well.
=> Add dump support for half float

src/gui/Src/Gui/AppearanceDialog.cpp
=> Always update the Example text's background color
