README.md

Just fixed a typo regarding the license (GPL) in the Readme file.

Fixed GPL-Typo (GLP vs GPL)

---

x64_dbg_gui/Project/Src/Gui/CPUSideBar.cpp
x64_dbg_gui/Project/Src/Gui/CPUSideBar.h
x64_dbg_gui/Project/Src/Gui/RegistersView.cpp
x64_dbg_gui/Project/Src/Gui/RegistersView.h

Fix SSE dependent classes not being properly aligned when created on the
heap. 
vc was warning about it, and it can possibly lead to bugs when SSE instructions are executed on unaligned members

Fix memory alignment

---

x64_dbg_dbg/_global.cpp
x64_dbg_dbg/capstone_wrapper.cpp
x64_dbg_dbg/debugger.cpp
x64_dbg_dbg/debugger_commands.cpp
x64_dbg_dbg/disasm_helper.cpp
x64_dbg_dbg/instruction.cpp
x64_dbg_dbg/stackinfo.cpp
x64_dbg_dbg/stringformat.cpp
x64_dbg_dbg/symbolinfo.cpp
x64_dbg_dbg/value.cpp

so it compiles with vc14. (Inline concatenation needs a space in between)
```cpp
//its
char* a = "ASD" "ASD"
//and not 
char* b = "ASD""ASD"
```
looks like vc12 is fine with it, vc14 not.

Fix inline string concatenation

---

src/dbg/label.cpp

It compared VAs (`Start`, `End`) with RVAs (`currentLabel.addr`).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/579)

Fixed LabelDelRange

---

src/dbg/memory.cpp

It would be optimal to log the failures, but I'm not sure whether it's OK to call `dputs` in there. Otherwise the code needs some reordering.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/581)

Continue running MemFindInMap even if unreadable pages exist

---

src/dbg/comment.cpp
src/dbg/label.cpp

Fixes an error message box which was displayed if the label/comment was changed from empty to empty
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/582)

Removing a label/comment which didn't exist shouldn't be an error

---

src/gui/Src/Gui/CPUDump.cpp
src/gui/Src/Gui/CPUDump.h
src/gui/Src/Gui/CPUStack.cpp
src/gui/Src/Gui/CPUStack.h

It's a common practice to place hardware access breakpoints directly on stack, so that when the breakpoint is hit, the SFX code will stop right before OEP. I've added the breakpoint menu to the CPU stack's context menu so that it will be more convenient.
I'm a new comer, knew about x64dbg today and played with it a whole day. I'm starting from this easy task. I'm learning about x64dbg's architecture and may be contributing more code in future days.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/642)

Add the ability to set breakpoints directly on stack

---

src/dbg/expressionparser.cpp
src/dbg/value.cpp

Now I can enter `gs:[30]` and jump to TEB of the thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/644)

DBG: Make it possible to reference segment registers using Goto

---

src/gui/Src/BasicView/Disassembly.cpp
src/gui/Src/Disassembler/capstone_gui.cpp
src/gui/Src/Disassembler/capstone_gui.h
src/gui/Src/Gui/AppearanceDialog.cpp
src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Utils/Configuration.cpp

**GUI: Apply unique color to unusual instructions**
Unusual instructions are privileged, unknown or IRET.
**PUSHF is recognised as push instructions.**
**GUI: Show label on comment area if no comments**
Labels in address columns are often hidden to save screen space. Allowing these labels to shown in comment area when nothing else needs to be shown improves working efficiency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/650)

GUI: Apply unique color to unusual instructions

---

src/gui/Src/Disassembler/capstone_gui.cpp

I don't understand why I/O commands are recognised as non-privileged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/658)

GUI: yet more unusual instructions

---

src/gui/Src/Gui/HexEditDialog.cpp

I changed the behavior of the binary edit dialog slightly to make it less painful to edit text with it.
1. Prevented the position cursor from jumping to the end of the line when inserting / deleting text.
2. 'Keep size' will set the ASCII / Unicode text box to overwrite mode. This prevents characters from getting pushed out of the text boxes.
Fixes #367 .
A cleaned solution would be to create a custom QLineEdit widget that displays a QByteArray as ASCII or Unicode and supports overwrite mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/670)

GUI: Fixed HexEditDialog behavior

---

src/gui/Src/Gui/CPUMultiDump.cpp

Add a native name for these dump windows to avoid crashing, but they are not used elsewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/677)

GUI: fix crashing (issue #676)

---

src/dbg/TraceRecord.cpp
src/dbg/_dbgfunctions.h
src/dbg/debugger.cpp
src/dbg/threading.h

In the crash dump I noticed multiple debug threads. This is quite strange since It's assumed only one process can be debuggged at a time. So I added a mutex locking the debug function.
Now if you holds CTRL+F2 down, the debugger will enter a wrong state, but the DB should not corrupt, and the program crashes less often.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/688)

db corruption is greatly reduced

---

src/gui/Src/Gui/GotoDialog.cpp
src/gui/Src/Gui/GotoDialog.ui

The dialog can already be resized automatically, but resizing was disabled before. Allowing resizing partially solves HIDPI problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/698)

Allow resize of goto dialog

---

src/gui/Src/Gui/HexEditDialog.cpp
src/gui/Src/Gui/HexEditDialog.h
src/gui/Src/Gui/HexEditDialog.ui
src/gui/Src/Gui/HexLineEdit.cpp
src/gui/Src/Gui/HexLineEdit.h
src/gui/Src/Gui/HexLineEdit.ui
src/gui/Src/QHexEdit/QHexEdit.cpp
src/gui/Src/QHexEdit/QHexEdit.h
src/gui/Src/QHexEdit/QHexEditPrivate.cpp
src/gui/Src/QHexEdit/QHexEditPrivate.h
src/gui/x64dbg.pro

I'm done with the cleaner version of PR #670.
- Fixes the ascii / unicode line edit behavior (Bug #367).
- Allows overwrite mode by pressing the INSERT key.
- Prevents immediately converting the unicode text back to hex (Bug #675)
Initializing the data the dialog should display is a bit odd right now. It is still done by calling *hexEdit.mHexEdit->setData(...);*, but it can be done just a single time (which should be fine right now, since *setData* is only called 0 or 1 times on each HexEditDialog instance).
I'd have to set the *mHexEdit* field to private and add some of the the QHexEdit api to the HexEditDialog to fix this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …

GUI: Implemented a custom QLineEdit

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/debugger.cpp
src/dbg/debugger_commands.cpp
src/dbg/instruction.cpp
src/dbg/instruction.h
src/dbg/x64_dbg.cpp
src/gui/Src/BasicView/ReferenceView.cpp
src/gui/Src/BasicView/ReferenceView.h

I implemented feature I mentioned in #669. After disabling gui messages, scripts and plugin commands that sets a lot breakpoints should run at least 5x faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/710)

Added api to supress gui message + add set breakpoint on every command in reference view

---

src/gui/Src/BasicView/Disassembly.cpp
src/gui/Src/BasicView/Disassembly.h
src/gui/Src/Gui/SettingsDialog.cpp
src/gui/Src/Gui/SettingsDialog.h
src/gui/Src/Utils/CachedFontMetrics.h
src/gui/Src/Utils/Configuration.cpp
src/gui/Src/Utils/Configuration.h

Now we don't need to restart the program to apply new disassembly settings.
And fix #715 (The disassembly interface is too messy)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/717)

Resolve UI bug (#715) and do not require restart on settings change

---

src/gui/Src/BasicView/AbstractTableView.cpp
src/gui/Src/BasicView/AbstractTableView.h
src/gui/Src/BasicView/HexDump.cpp
src/gui/Src/Gui/BreakpointsView.cpp
src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/CPUMultiDump.cpp
src/gui/Src/Gui/CPUWidget.cpp
src/gui/Src/Gui/CallStackView.cpp
src/gui/Src/Gui/HandlesView.cpp
src/gui/Src/Gui/MemoryMapView.cpp
src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/SEHChainView.cpp
src/gui/Src/Gui/ScriptView.cpp
src/gui/Src/Gui/SettingsDialog.cpp
src/gui/Src/Gui/SettingsDialog.h
src/gui/Src/Gui/SettingsDialog.ui
src/gui/Src/Gui/StatusLabel.cpp
src/gui/Src/Gui/ThreadView.cpp
src/gui/Src/Utils/CachedFontMetrics.h
src/gui/Src/Utils/Configuration.cpp
src/gui/Src/Utils/MiscUtil.cpp
src/gui/Src/Utils/MiscUtil.h
src/gui/Src/main.cpp

I add a new tab "GUI" in the settings dialog to set the new option. By default FPU registers are shown as big-endian. Edit float registers dialog is not changed by now since the byte order is explicitly stated there. The tab "GUI" will be populated with various settings such as the option to save column width or dialog positions, as well as current language.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/730)

Fix multiple issues

---

src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Utils/Configuration.cpp

The current analyze algorithm is unsuitable for use in object-oriented application. I am debugging an executable now, and only "analyze single function" is reliable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/736)

GUI: add shortcut for "analyze single function"

---

src/gui/Src/Gui/MainWindow.cpp

All the softwares search "OllyDbg" window in the system. Will x64dbg enjoy comparable fame?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/759)

Window title obfuscation

---

src/dbg/_plugin_types.h
src/dbg/_plugins.h
src/dbg/database.cpp

This is the code for #763 
All plugin data is stored inside "plugins" object.
This branch has not been tested. It needs to be tested with a working plugin.
CB_LOADDB/CB_SAVEDB callback types are introduced with argument type PLUG_CB_LOADSAVEDB.
_Since all the plugin callbacks are supplied with a JSON object, should we increment its reference count before every plugin callback, or left that as a responsibility of the plugin?_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/766)

Plugin database storage

---

src/dbg/TraceRecord.cpp
src/gui/Src/Gui/CPUSideBar.cpp

#769 now fixed with the new appearance:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/788)

fix 2 issues

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/exe/LoadResourceString.h
src/exe/Strings.rc
src/exe/resource1.h
src/exe/x64_dbg_exe.cpp
src/exe/x64_dbg_exe.vcxproj
src/exe/x64_dbg_exe.vcxproj.filters
src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/CPUDump.cpp
src/gui/Src/Gui/LogView.cpp
src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/Gui/MemoryMapView.cpp
src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/ShortcutsDialog.cpp
src/gui/Src/Gui/SymbolView.cpp
src/gui/Src/Utils/Configuration.cpp
src/launcher/x64_dbg_launcher.cpp
src/launcher/x64_dbg_launcher.vcxproj
src/launcher/x64_dbg_launcher.vcxproj.filters

The translated strings are stored in "Strings.rc" and loaded via `LoadString`. `LoadString` is the only viable way to get translated strings before the GUI is loaded.
The shortcuts added are :
- ActionEditBreakpoint
- ActionToggleLogging
- ActionAllocateMemory
- ActionFreeMemory
- ActionSyncWithExpression
- ActionEntropy
- ActionCopyAllRegisters
- ActionMarkAsUser
- ActionMarkAsSystem
- ActionMarkAsParty
- AnalysisRemoveAnalysisFromModule
- AnalysisRemoveAnalysisFromSelection
- AnalysisTreatSelectionAsByte
- AnalysisTreatSelectionAsASCII
- AnalysisTreatSelectionAsUNICODE
- ActionSetHwBpE
- ActionRemoveHwBp
- DebugTraceIntoConditional
- DebugTraceOverConditional
- DebugEnableTraceRecordBit
- DebugTraceRecordNone
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Translate the launcher and add more shortcuts

---

src/gui/Src/BasicView/ReferenceView.cpp
src/gui/Src/Gui/AppearanceDialog.cpp
src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/CPUDump.cpp
src/gui/Src/Gui/MemoryMapView.cpp
src/gui/Src/Gui/PatchDialog.cpp
src/gui/Src/Utils/MiscUtil.cpp
src/gui/Src/Utils/MiscUtil.h

Reduce code size. Make programming easier. Too lazy to convert all `QMessageBox` into `SimpleErrorBox`, however I'm using it in the unfinished watch view code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/818)

Add simple message box util function

---

src/gui/Src/Gui/ReferenceManager.cpp

added showCpu() signal emissions when all or last reference tab is removed from References widget.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/854)

fix issue 518: switch to CPU view after closing last reference view tab.

---

src/bridge/_global.cpp
src/bridge/_global.h
src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/_dbgfunctions.h
src/dbg/breakpoint.cpp
src/dbg/debugger.cpp
src/dbg/debugger.h
src/dbg/taskthread.h
src/dbg/thread.cpp
src/gui/Src/BasicView/AbstractTableView.cpp
src/gui/Src/BasicView/AbstractTableView.h
src/gui/Src/BasicView/Disassembly.cpp
src/gui/Src/BasicView/HistoryLineEdit.cpp
src/gui/Src/BasicView/HistoryLineEdit.h
src/gui/Src/BasicView/StdTable.cpp
src/gui/Src/BasicView/StdTable.h
src/gui/Src/Bridge/Bridge.cpp
src/gui/Src/Bridge/Bridge.h
src/gui/Src/Exports.h
src/gui/Src/Gui/CommandLineEdit.cpp
src/gui/Src/Gui/CommandLineEdit.h
src/gui/Src/Gui/LogView.cpp
src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/Gui/SymbolView.cpp
src/gui/Src/Gui/ThreadView.cpp
src/gui/Src/Gui/TimeWastedCounter.cpp
src/gui/Src/Gui/TimeWastedCounter.h

The added logic is in deferable taskthreads; they now check the current latency and defer if that latency is too high. This should prevent any additional events from being sent to QT; which should put a firm limit on how backed up the queue can get during heavy load. 
Also modified the event count logic so it took elapsed time into account. Without this logic, the number reported was based on message processing timing, which fluctuates during load; even when the messages are added at one second intervals.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/834)

Added ability to roughly measure UI latency; code to try and maintain that latency at <50ms

---

src/dbg/debugger.cpp

In "rtr", the debugger cannot stop tracing when the executable uses some prefixed retns such as "40 C3"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/869)

fix wrong behaviour with prefixed retn

---

src/dbg/debugger_commands.cpp
src/dbg/threading.cpp
src/dbg/threading.h
src/dbg/x64_dbg.cpp

Don't know if this is the right solution, but at least I can stop the debugger without task manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1007)

don't halt

---

src/launcher/x64_dbg_launcher.cpp

Fixed wow64 redirection. Moved disable before the call to GetFileArchitecture()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1013)

Fixed wow64 redirection. 

---

src/gui/Src/Gui/CPUDump.cpp
src/gui/Src/Gui/CPUDump.h
src/gui/Src/Gui/CPUInfoBox.cpp
src/gui/Src/Gui/CalculatorDialog.cpp
src/gui/Src/Gui/HexEditDialog.cpp
src/gui/Src/Gui/HexLineEdit.cpp

* Add last code page to the context menu of the dump
* View the source string in selected code page before modifying it in hex editor.
* Try to use less `toLatin1` since it is not compatible with Windows ASCII convention. We should use `toLocal8Bit` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1023)

Use last code page conveniently

---

src/gui/Src/Gui/EditFloatRegister.cpp
src/gui/Src/Gui/EditFloatRegister.h
src/gui/Src/Gui/EditFloatRegister.ui
src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/RegistersView.h

-   Edit MMX registers with the same dialog used to edit XMM registers, with short, long and float data types.
-   Show a tooltip for the flags register to help the user to understand the register.
-   Respect configurated endianess in the edit floating-point register dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1098)

Registers view enhancements

---

src/gui/Src/Gui/CPUArgumentWidget.cpp
src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/RegistersView.h
src/gui/Src/Utils/Configuration.cpp

-   The descriptions for registers (eg, "Nonzero"), have been internationalized.
-   More help information for registers.
-   Can display SIMD registers (XMM and YMM) in float, double or integer format.
-   Adds icons for context menu in arguments list.
-   Can copy small arguments in arguments list now.
-   Other minor fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1101)

registers view and cpu argument enhancements

---

src/dbg/_global.cpp
src/dbg/_global.h
src/dbg/commands/cmd-debug-control.cpp

Allow the user to debug dotNET applications. Note it only changes the file validation function to let dotNET applications pass the test, it does not introduce a pleasant user experience when debugging dotNET applications. The user is required to start dotNET application with the right architecture of x64dbg, and the user must set x64dbg to pause at system breakpoint. x64dbg cannot pause at the entry point of the dotNET application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1124)

Allow debugging dotNET applications

---

src/gui/Src/BasicView/AbstractTableView.cpp
src/gui/Src/BasicView/AbstractTableView.h
src/gui/Src/BasicView/LabeledSplitter.cpp
src/gui/Src/BasicView/LabeledSplitter.h
src/gui/Src/Bridge/Bridge.h
src/gui/Src/Gui/BreakpointsView.cpp
src/gui/Src/Gui/HandlesView.cpp
src/gui/Src/Gui/LogStatusLabel.cpp
src/gui/Src/Gui/LogView.cpp
src/gui/Src/Gui/LogView.h
src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/RegistersView.h
src/gui/Src/Gui/SettingsDialog.ui

The state of custom splitters can be saved now. It only works for breakpoints view and handles view. Also adds a "close" event instead of relying on the destructor to save GUI state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1125)

Save Splitter State

---

src/dbg/_exports.cpp
src/dbg/_plugins.h
src/dbg/plugin_loader.cpp

Closes #445.
Tested with a simple plugin that filters out a specific symbol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1135)

Added a plugin callback that allows filtering dbghelp emitted symbols.

---

src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/RegistersView.h

This new action will restore the changes made to a register to the previous value.
There's a small shortcoming when a register is changed multiple times (e. g. first by an instruction then by the user). That can be fixed later on by saving the changes to a stack and implementing proper undo/redo.
Closes #966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1142)

GUI: Add undo register context menu action

---

src/gui/Src/Gui/MemoryMapView.cpp
src/gui/Src/Gui/MemoryMapView.h

This adds a *Goto* menu (analogous to one in the CPU view) to the memory map view with two sub actions.
1. Goto->Origin (new)
This will select the page where the cip is.
2. Goto->Expression
This is the already existing *Find address page* action.
Closes #1084.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1146)

GUI: Add Goto->Origin action to the MemoryMapView

---

src/gui/Src/Gui/CPUSideBar.cpp

This internal instruction has too many strings for translation, which wastes translators' time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1150)

remove internal instruction "capstone"

---

src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/Gui/MainWindow.h
src/gui/Src/Gui/MainWindow.ui
src/gui/Src/Gui/TabWidget.cpp
src/gui/Src/Gui/TabWidget.h
src/gui/Src/Utils/Configuration.cpp

This allows users to cycle through their attached tabs. Detached tabs will not be cycled through.
The default hotkeys are Ctrl+Tab/Ctrl+Shift+Tab.
Closes  #1017.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1152)

GUI: Add View->Next/Previous Tab actions

---

src/dbg/_exports.cpp

I'm a first time contributor and am not overly familiar with x86 assembly, but I think this should do the trick. (Though perhaps `instr.arg[0].segment` also needs checking, I'm not totally sure.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1164)

DBG: add autocomment for call $0 (closes #940)

---

src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/CPUDisassembly.h

Closes #953.
Could be pulled out of the copy menu but it seems logical for it to be there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1186)

Added Symbolic Name copy to copy context meny in CPU disassembly window.

---

src/gui/Src/Gui/DisassemblerGraphView.cpp

additional fix for pull request https://github.com/x64dbg/x64dbg/pull/1198 - remove unnecesary white bar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1205)

GUI: remove unnecesary bar in graph image

---

src/gui/Src/BasicView/SearchListViewTable.cpp
src/gui/Src/BasicView/SearchListViewTable.h
src/gui/Src/Gui/CustomizeMenuDialog.cpp
src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/Gui/SourceView.cpp
src/gui/Src/Gui/SymbolView.cpp
src/gui/Src/Utils/Configuration.cpp

*  Show traced address green in the source and references view.
*  Customize menu of source view, although there is only 2 items now and you must first open a source view to customize it.
*  A placeholder tip in "Mark as party..." to remind the user that 0 is user module and 1 is system module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1209)

traced background in references and source

---

src/dbg/commands/cmd-script.cpp
src/dbg/commands/cmd-script.h
src/dbg/x64dbg.cpp

New command "printstack" or "logstack". Sample output:
11 call stack frames (RIP = 000007FEE427CCE4 , RSP = 00000000001CEFF8 , RBP = 00000000001CF4C0 ):
00000000001CEFF8 return to ntdll.0000000077CA6A98 from <x64gui._DllMainCRTStartup>
00000000001CF1C8 return to ntdll.0000000077CA686E from ntdll.0000000077CA6A98
00000000001CF3C8 return to ntdll.0000000077C95FCF from ntdll.0000000077CA686E
00000000001CF438 return to kernelbase.000007FEFDAF0176 from ntdll.0000000077C95FCF
00000000001CF4B8 return to nvd3d9wrapx.000007FEFA355845 from kernelbase.000007FEFDAF0176
00000000001CF6B8 return to x64bridge.000007FEE9F566CE from nvd3d9wrapx.000007FEFA355845
00000000001CF6E8 return to x64dbg.000000013F0B1FD0 from x64bridge.000007FEE9F566CE
00000000001CF748 return to x64dbg.000000013F0B2555 from …

print stack trace

---

src/gui/Src/BasicView/HexDump.cpp
src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Utils/Configuration.cpp

Adds a shortcut for ActionCopyRva, set to nothing by default.
Also makes Shift-Middle Click copy the RVA instead of the address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1232)

GUI: Add "Copy RVA" shortcut

---

src/dbg/_exports.cpp
src/dbg/stackinfo.cpp
src/dbg/stackinfo.h
src/gui/Src/Gui/CPUStack.cpp
src/gui/Src/Gui/CPUStack.h
src/gui/Src/Gui/CallStackView.cpp
src/gui/Src/Gui/CallStackView.h
src/gui/Src/Gui/LogView.cpp
src/gui/Src/Utils/Configuration.cpp

Bug: log hyperlink never works on 32-bit platform
Feature: Show suspected/active call stack frame. Active stack frames are the same as the current ones. When showing suspected call stack frames, then instead of using the structure of call stack frame to walk the stack, it will search for the entire stack to find an address that is possible as a return address. This will typically result in more call stack frames available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1282)

Show suspected call stack frame, and fix a bug

---

src/exe/crashdump.cpp
src/exe/crashdump.h

This should fix scenarios like #1311 where the crashdump has missing stack information (making it useless for me). I think it's related to FASTFAIL/Windows 10, but not really sure.
It does *not* fix 1311 though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1338)

Intercept more functions for crashdumps

---

src/gui/Src/Gui/CalculatorDialog.ui
src/gui/Src/Gui/EditBreakpointDialog.cpp
src/gui/Src/Utils/MiscUtil.cpp
src/gui/Src/Utils/MiscUtil.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1346)

Add symbolic name of the breakpoint to be edited, resolves #1326

---

src/gui/Src/BasicView/StdTable.cpp
src/gui/Src/Bridge/Bridge.cpp
src/gui/Src/Bridge/Bridge.h
src/gui/Src/Gui/LogStatusLabel.cpp
src/gui/Src/Gui/LogStatusLabel.h
src/gui/Src/Gui/LogView.cpp
src/gui/Src/Gui/LogView.h

Test script:
```
log "Start Performance Testing"
mov $perf,GetTickCount()
mov $i,0x4000
looping:
log {$i}
log {$i*2}
mov $i,$i-1
test $i,$i
jnz looping
nop
nop
mov $perf1,GetTickCount()-$perf
mov $perf,$perf1
log "Performance Testing Finished!Performance: {u:$perf}"
```
Test is conducted by monitoring the user CPU time of the GUI thread of x64dbg before and after running above script. $pref is not sync with GUI updates so it cannot be used. Results:
Old, UTF-8, Log Enabled: 6.9888448
Old, UTF-8, Log Disabled: 1.1388073
Old, UTF-16, Log Enabled: 6.0060385
Old, UTF-16, Log Disabled: 0.312002
New, UTF-8, Log Enabled: 4.6644299 (-33.3%)
New, UTF-8, Log Disabled: 0.3900025 (-65.8%)
New, UTF-16, Log Enabled: 5.1012327 (-15.1%)
New, UTF-16, Log Disabled: 0.1092007 (-65%)
---
This change is [<img …

optimized logging speed

---

src/dbg/commands/cmd-misc.cpp
src/dbg/commands/cmd-misc.h
src/dbg/x64dbg.cpp
src/gui/Src/Gui/AttachDialog.cpp
src/gui/Src/Gui/AttachDialog.h
src/gui/Src/Gui/AttachDialog.ui

Get or set the configuration of x64dbg. It can also be used to load and store configuration specific to the script in the configuration file of x64dbg.
``arg1``: Section name of the INI file.
``arg2``: Key name of the INI file.
\[``arg3``\]: Optional new value of the configuration. If this argument is set to a number, it will be stored in the configuration file and ``$result`` is not updated. If this argument is not set, the current configuration will be read into ``$result``.
This command sets ``$result`` to the current configuration number if ``arg3`` is not set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1355)

config command

---

src/dbg/_exports.cpp
src/dbg/debugger.cpp
src/dbg/debugger.h
src/gui/Src/Gui/SettingsDialog.cpp
src/gui/Src/Gui/SettingsDialog.h
src/gui/Src/Gui/SettingsDialog.ui

fixes #1312
Added an engine setting, "Enable Verbose Exception Logging", which determines if the exinfo command is executed in the exception callback.  Enabled by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1358)

#1312 disable exinfo on exceptions

---

src/dbg/commands/cmd-analysis.cpp

resolves #1331 
I removed the current ExceptionInformation logging code, but it may be a good idea to have some handling for undocumented use of this var.  What do you think?
preview for each access violation case:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1361)

added extra info prints for access violation exceptions for the exinfo command

---

src/dbg/commands/cmd-analysis.cpp
src/dbg/symbolinfo.cpp
src/gui/Src/Gui/SettingsDialog.cpp

Update Microsoft symbol server URL to https://msdl.microsoft.com/download/symbols. This is the default sympath in WinDbg 10.0.14321.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1300)

Use HTTPS for Microsoft symbol server URL

---

src/gui/Src/Gui/TabBar.cpp

#1339
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1367)

fixed additional buttons on tab bar

---

src/gui/Src/BasicView/Disassembly.cpp
src/gui/Src/BasicView/Disassembly.h
src/gui/Src/Bridge/Bridge.cpp
src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/CPUDisassembly.h

- Statusbar message update on disassembly data copy (Issue #1280)
- Extended info on statusbar (like in dump window) of selected
instructions in the disassembly window
- Copy multiselected Addreses(VA/RVA) in the disassembly window
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1363)

Disassembler copying and statusbar enhancements

---

src/dbg/assemble.cpp
src/dbg/disasm_helper.cpp
src/dbg/expressionfunctions.cpp
src/dbg/stringutils.cpp
src/dbg/undocumented.h
src/dbg/value.cpp
src/dbg/x64dbg_dbg.vcxproj
src/dbg/x64dbg_dbg.vcxproj.filters
src/gui/Src/Gui/AppearanceDialog.cpp
src/gui/Src/Gui/BreakpointsView.cpp
src/gui/Src/Gui/BreakpointsView.h
src/gui/Src/Gui/CPUInfoBox.cpp
src/gui/Src/Gui/EditFloatRegister.ui
src/gui/Src/Gui/RegistersView.cpp

*  Highlight segment register from reg view, and remove push/pop segment register to/from the stack.
*  Disable font kerning to make the width of text and the background of it consistent with variable-width font
*  Changed some BreakpointViewTable back to StdTable because they does not contain a memory address.
*  info box: change "dword[eax]" to "dword ptr[eax]"
*  Edit floating point register: correctly label byte offset of high part, from 0x10 to 0x1F
*  Use IsTextUnicode, although the behaviour is still the same. It is now possible to write a plugin that hooks IsTextUnicode to support better Unicode text detection. And do not escape or corrupt valid UTF-8 character. It is now possible to display Unicode text in the auto comment without corruption or escape if IsTextUnicode detects …

Highlight segment register from reg view

---

src/dbg/memory.cpp

fixes #1374
To debug this I hooked NtProtectVirtualMemory in x64dbg using an injected dll.  All VirtualProtectEx calls (excluding the call in MemSetPageRights which isn't executed) followed this chain:
<pre>
x64dbg.dll!MemRead
TitanEngine.dll!MemoryReadSafe
- ReadProcessMemory
if this fails
- VirtualProtectEx PAGE_EXECUTE_READWRITE
- ReadProcessMemory
- VirtualProtectEx oldprot
</pre>
This is the hook output when viewing the noaccess page region boundary from the [POC repo](https://github.com/changeofpace/x64dbg-Anti-Debug-POC).  '>' denotes a print before a call to the original NtProtectVirtualMemory, '<' is after:
<pre>
000000013F150000  0000000000001000  x64dbg anti-debug poc.exe                                IMG  -R---
000000013F151000  0000000000009000   ".text" …

fix incorrectly restored page protection for cross-boundary memory reads

---

src/dbg/memory.cpp

fixed a bug where fallbackCookie would use a previous session's process cookie if MemInitRemoteProcessCookie failed before the brute-force loop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1418)

initialize fallbackCookie to zero in MemInitRemoteProcessCookie

---

src/gui/Src/Gui/LogView.cpp

Reverted a change to LogView::addMsgToLogSlot because QString::toHtmlEscaped does not convert spaces to &nbsp.
https://github.com/qt/qtbase/blob/dev/src/corelib/tools/qstring.cpp#L10760
ref: https://github.com/x64dbg/x64dbg/commit/e295f56c9c74c247618cb1160f5397169521ac27#diff-b6006fbcabfc49bd593d76e5984c4610L232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1439)

Preserve horizontal spacing in log messages.

---

src/dbg/commands/cmd-breakpoint-control.cpp

Normal breakpoints are not removed if SetBPX fails in cbDebugSetBPX.  The invalid breakpoint appears in the breakpoint tab and is highlighted in the disassembly view:
attempting to set the bp:
removing the bp:
I removed the MemIsValidReadPtr check because BpAdd will fail if MemIsValidReadPtr(addr) is false.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1460)

Do not add breakpoint if SetBPX fails.

---

src/gui/Src/Gui/CPUSideBar.cpp
src/gui/Src/Gui/CPUSideBar.h
src/gui/Src/Gui/DisassemblerGraphView.cpp

*  Fixed crash when the user decompile when not debugging.
*  Double-click on the checkbox will select the folding segment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1473)

fixed a crash and enable user to dblclick on folding box

---

src/gui/Src/Disassembler/capstone_gui.cpp
src/gui/Src/Disassembler/capstone_gui.h
src/gui/Src/Gui/SettingsDialog.cpp
src/gui/Src/Gui/SettingsDialog.h
src/gui/Src/Gui/SettingsDialog.ui
src/gui/Src/Utils/Configuration.cpp

The user can configure it in the settings dialog to hide module name if the memory address is within the same page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1474)

√ Allow hiding local module name for memory addresses in the same page.

---

src/dbg/thread.cpp
src/dbg/thread.h
src/dbg/undocumented.h

I noticed threads were always being shown as being in the "executive" wait state, which I found a bit silly because WrExecutive is normally reserved for the kernel. Taking a look at the source I found ThreadGetWaitReason was actually unimplemented :P So that would explain it.
This is an implementation that uses NtQuerySystemInformation(SystemProcessInformation), the only possible way to get the thread wait reason.
It is monstrously inefficient because it gets info on all running processes AND all of their threads (even though we only need one piece of info on one thread). It could be made more efficient by at least caching the results for the whole process so that ThreadGetWaitReason would only have to be called once per process instead of for every thread. But that would require some …

Add wait reason to threads list

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/TraceRecord.cpp
src/dbg/commands/cmd-general-purpose.cpp
src/dbg/commands/cmd-thread-control.cpp
src/dbg/debugger.cpp
src/dbg/debugger.h
src/dbg/expressionparser.cpp
src/dbg/handles.cpp
src/dbg/jit.cpp
src/dbg/memory.h
src/dbg/serializablemap.h
src/dbg/taskthread.h
src/dbg/watch.cpp

This PR makes x64dbg compile and run using Clang/C2 from VS2017. The main goal of this is to add Clang's impressive diagnostics and warnings for additional compile time error checking. (There are a **lot** of warnings currently, but I've kept the changes to the minimum required to get the project to compile.)
Some notes:
- The launcher (x96dbg.exe) still requires MSVC to compile due to the ATL headers being... well, special. I haven't managed to get the project to compile without modifying the ATL headers, which is probably going a bit too far.
- The GUI DLL also requires MSVC, but this is more due to Qt's build system's lack of support for Clang/C2. It could probably be made to work with enough violence (given that Qt does support Clang/LLVM on Windows), but I'm not really interested in …

Add support for Clang compilation

---

README.md

updated badges for telegram and freenode to use shields.io. this will ensure that the resolution is correct on all devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1503)

Updated telegram & freenode badge

---

src/gui/Src/Gui/SymbolView.cpp

Fixed #1566. This has been tested on a DLL in "C:\Program Files (x86)\...".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1567)

fixed #1566

---

src/dbg/database.cpp
src/dbg/database.h
src/dbg/debugger.cpp
src/dbg/module.cpp
src/dbg/module.h

Prepare for run trace subsystem. This approach reads the hash from the database and compare it to the debuggee when the debuggee is loaded. The reverse is not possible because when debugging a DLL, the database loads before the debuggee loads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/x64dbg/x64dbg/1570)

Warn the user about mismatch of database and executable

---

src/gui/Src/Gui/CPUMultiDump.cpp
src/gui/Src/Gui/CPUWidget.cpp
src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/RegistersView.h
src/gui/Src/Gui/TabWidget.cpp

Follow in dump N now behaves correctly. Registers view can use the tab name of dump tabs, instead of "Dump n"

Fixed issue with detached dumps

---

src/dbg/command.cpp
src/dbg/stringutils.cpp
src/dbg/value.cpp
src/gui/Src/Gui/LocalVarsView.cpp

I've found some issues with Cppcheck and prepared this simple patch and list of interesting errors (most of raw results I filtered, e.g. related to a different argument names in header/cpp files).
It could be great if you can review both of it
[src/gui/Src/Gui/DisassemblyPopup.cpp:121]: (warning, inconclusive) Access of moved variable instruction.
[src/gui/Src/BasicView/AbstractTableView.cpp:1137]: (style) Condition 'totalWidth<=this->viewport()->width()' is always true
[src/gui/Src/Gui/CPUStack.cpp:639]: (style) Redundant condition: If 'frame > 0', the comparison 'frame != -1' is always true.
[src/dbg/module.cpp:63]: (error) Using 'memset' on struct that contains a 'std::vector'.
[src/dbg/symbolinfo.cpp:160]: (style, inconclusive) Checking if unsigned variable 'modList.size()' is less …

Small code improvement

---

src/gui/Src/Disassembler/QBeaEngine.cpp
src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/Gui/TabWidget.cpp
src/gui/Src/Gui/TabWidget.h
src/gui/Src/Utils/MiscUtil.cpp
src/gui/Src/Utils/MiscUtil.h

Catching temporaries by a non-const reference is a VS extension and it'd fail to compile in a newer VS versions by default (tested in  VS2017).

Fix standard conformance issues

---

src/gui/Src/Gui/TabBar.h
src/gui/Src/Gui/TabWidget.cpp

fixes #1741
Btw, it wouldn't go unnoticed if the project used [new signal/slot syntax](https://wiki.qt.io/New_Signal_Slot_Syntax) (which is already quite old ;P).

Fix tab detaching

---

src/gui/Src/BasicView/StdTable.cpp
src/gui/Src/BasicView/StdTable.h

This allows selecting multiple rows in e. g. the Breakpoints view
without having to use the mouse.
New hotkeys:
- Select all: (ctrl+a)
- Select first row (ctrl+home)
- Select last row (ctrl+end)
- Expand selection upwards (shift+up)
- Expand selection downwards (shift+down)
Related issue: #1304

GUI: add multiselect hotkeys to StdTable

---

src/gui/Src/Gui/DisassemblerGraphView.cpp

If you follow a jump or a call, and click on '-', you don't go back to the jump or the call (as in the regular CPU view), but to a previous, non-relevant command in the graph. This commit tries to fix this.
I haven't compiled or checked this. Please verify, or I'll do it myself later.
__Edit:__ Tested AppVeyor's build, seems to be working.

Remember navigation source in graph history

---

src/gui/Src/Disassembler/QBeaEngine.cpp
src/gui/Src/Disassembler/capstone_gui.cpp
src/gui/Src/Disassembler/capstone_gui.h

```
<Baboon> hi
<Baboon> it seems that jmp far are not correctly decoded by x64
<Baboon> (10/10/2017 version, didn't test the latest)
[...]
<Baboon> I'll download the last version
<Baboon> last version, same bug : "\xEA\xEF\xB5\x0D\x77\x33\x00"
<Baboon> got an empty string instead of /b meta
```
This fixes the issue.

Add tokenizer support for pointer operands

---

src/bridge/_global.h
src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/_exports.cpp
src/dbg/_exports.h

This PR adds `DbgGetRegDumpEx` to the public bridge API (prerequisite for implementing #1776 without breaking compatibility with existing plugins).
There is some minor unavoidable overlap between the two PRs such as adding `LASTSTATUS` to bridgemain.h. Calling `DbgGetRegDumpEx` with `sizeof(REGDUMP_V2)` also currently doesn't do anything useful, I've left that for the other PR which I can rebase after this is merged.

Add DbgGetRegDumpEx to bridge API

---

src/gui/Src/Gui/ShortcutsDialog.cpp

Closes #1256.  
Specifically, the current behavior is:  
- Overriding global hotkeys is not allowed at all.
- Overriding a local shortcut with a global one is silent.
- Overriding a local shortcut by a local one asks for confirmation.

Overriding a non global action hotkey now asks for confirmation.

---

src/gui/Src/Gui/RegistersView.cpp

This PR fixes issue #1333. It should be now possible to change the CPU view into highlight mode (H key) and select one of the segment registers in the Registers View.

GUI: handle highlighting segment registers in RegistersView

---

src/gui/Src/Disassembler/CsQBeaEngine.cpp
src/gui/Src/Gui/BreakpointsView.cpp

This PR fixes the following 2 compile errors that occur when building using the MSVC2017 toolchain in Qt Creator:
1. Trying to bind an rvalue to non-const reference:
`..\gui\Src\Disassembler\CsQBeaEngine.cpp(274): error C2440: 'initializing': cannot convert from 'QHash<ENCODETYPE,CsQBeaEngine::DataInstructionInfo>::iterator' to 'QHash<ENCODETYPE,CsQBeaEngine::DataInstructionInfo>::iterator &'
..\gui\Src\Disassembler\CsQBeaEngine.cpp(274): note: A non-const reference may only be bound to an lvalue`
2. Declaring a struct inside a lambda function:
`..\gui\Src\Gui\BreakpointsView.cpp(145): error C2327: 'BreakpointsView::reloadData::<lambda_14f74381a4291d4224dc2543f7a47ae4>::__this': is not a type name, static, or enumerator
..\gui\Src\Gui\BreakpointsView.cpp(145): error C2065: '__this': …

MSVC 2017 compile fixes

---

src/dbg/commands/cmd-memory-operations.cpp
src/dbg/stringformat.cpp

fixes #1778 
`stringformatinline(argv[1])` was replacing a file path with \\n with a newline. For example, C:\Users\Desktop\Me\nogood.bin would cause `name = "C:\\Users\\Desktop\\Me\nogood.bin"`.

DBG: fix saving CPUDump and mmap dump to file

---

src/gui/Src/Gui/MemoryMapView.cpp

Sorting more of the memory map headers is useful. Finding reflective DLL injection ore other RWE regions is a lot quicker when able to sort.

GUI: sortable memory map headers for type and protections

---

src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/CPUDump.cpp

like IDA, set init value of current selected address. It's convenient when there is no shortcut binding for copy file offset, but goto file offset having a shortcut CTRL+SHIFT+G, you can press CTRL+SHIFT+G and CTRL+C to copy file file offset of current selected address in CPU disassembler or dump window.

Let goto file offset dialog has a init value of current selected address

---

src/gui/Src/BasicView/SearchListView.cpp

In some case, the right panel in symbol view are wrong when text changed in filter textbox of left panel.
`mCurList->setSingleSelection` cause the update in right panel, and should be called after `mSearchList->reloadData()`. 
Also prevent double call setSingleSelection to improve performance.

Fix a bug in symbol view

---

src/gui/Src/Disassembler/capstone_gui.cpp
src/gui/Src/Disassembler/capstone_gui.h
src/gui/Src/Disassembler/cs_capstone_gui.cpp
src/gui/Src/Disassembler/cs_capstone_gui.h
src/gui/Src/Gui/SettingsDialog.cpp
src/gui/Src/Gui/SettingsDialog.h
src/gui/Src/Gui/SettingsDialog.ui
src/gui/Src/Utils/Configuration.cpp

Added two settings in the Disasm tab for hiding pointer sizes as well as segments which aren't FS or GS.

Added settings to hide pointer sizes and default segments

---

src/gui/Src/Gui/CPUDisassembly.cpp

Before this change, `CPUDisassembly::setupFollowReferenceMenu` would not add `Constant` to the list if `Address` had the same value. I think it's okay to show two entries even if they have the same value for consistency. Let me know what you think.
fixes #832

GUI: show Follow->Constant even if same as Address

---

src/dbg/debugger.cpp

See #1759 for discussion (but scroll to the bottom, that ticket discusses like 3 separate bugs in one thread).
In the case that x64dbg starts the debuggee process, it keeps two unneeded handles around with `PROCESS_ALL_ACCESS` and `THREAD_ALL_ACCESS` rights respectively. These are duplicated in `nt!DbgkpOpenHandles` when the first debug event (`CREATE_PROCESS_DEBUG_EVENT`) is sent. The latter two handles are automatically closed by kernel32 after `EXIT_PROCESS_DEBUG_EVENT` is handled. The original handles from `CreateProcess` (done by TitanEngine) are never closed however. You can check this by starting a debug session, stopping the process, restarting the session, and so on: Process Hacker will show a leaked process handle in x64dbg.exe to a non-existent process for each session that was …

Do not keep duplicate process and initial thread handles around

---

src/gui/Src/Gui/ThreadView.cpp

As the title suggests. If you double click on the thread it will also now jump to the IP.

Jump to thread IP by double clicking.

---

src/dbg/breakpoint.cpp
src/gui/Src/BasicView/SearchListView.cpp
src/gui/Src/BasicView/SearchListView.h
src/gui/Src/Gui/BreakpointsView.cpp
src/gui/Src/Gui/SymbolView.cpp

This is a tracking branch. Currently it adds a special format DLL:$RVA that BpGet recognizes even if DLL is not loaded, so commands like "bpc" can remove these breakpoints. GUI is under development.
Other bugs fixed:
* Allow going to entrypoint of libstdc++-6.dll in SymbolsView

Allow editing and removing inactive breakpoints

---

src/gui/Src/BasicView/AbstractStdTable.cpp
src/gui/Src/BasicView/AbstractStdTable.h
src/gui/Src/BasicView/Disassembly.cpp
src/gui/Src/BasicView/Disassembly.h
src/gui/Src/BasicView/HexDump.cpp
src/gui/Src/BasicView/HexDump.h
src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/RegistersView.h

Arrow keys are now used to select in dump, not scroll in dump. Dump will scroll when selection is out of viewport. Shift key is to be supported.

Use keys to select in dump

---

src/gui/Src/Tracer/TraceBrowser.cpp
src/gui/Src/Tracer/TraceBrowser.h
src/gui/Src/Tracer/TraceFileReader.cpp
src/gui/Src/Tracer/TraceFileReader.h

Previously when you close a trace file, it will not stop recording a trace. Now it does. Added a new action to close and delete current trace to save your disk space.

Close, stop and delete current trace file

---

src/dbg/TraceRecord.cpp
src/dbg/commands/cmd-undocumented.cpp
src/dbg/disasm_helper.cpp

Previously when you trace while recording a trace over a far jump, such as an API call, x32dbg crashes.

Fixed a crash when tracing into far jump

---

src/gui/Src/Gui/AppearanceDialog.h
src/gui/Src/Gui/WordEditDialog.h

I think this was introduced in Qt11. I saw a similar error in RPCS3 repo regarding forward declaration.
If anyone else could validate that it doesn't build on 5.11.1 without this fix would be great as I don't work on C++ that much.
Happy Hacktoberfest!

GUI: Fix build for latest Qt

---

src/gui/Src/Gui/RegistersView.cpp

_InitMappings()_ is now called before _getEstimateHeight()_.
_getEstimateHeight()_ calculates the height of the registers view. The calculation is based on _mRowsNeeded_ which is set in InitMappings(). However, _getEstimateHeight()_  was called before _InitMappings()_ and therefore the calculation was based on an uninitialized variable.

FIXED: Uninitialized variable when calculating registers view height

---

src/dbg/module.cpp
src/dbg/module.h
src/dbg/symbolinfo.cpp

This PR fixes issue #2003, the OptionalHeader.AddressOfEntryPoint display broke after the symbols ui refactor. This PR restores the original functionality using the new API.

DBG: add OptionalHeader.AddressOfEntryPoint to the displayed symbols

---

src/bridge/bridgemain.h
src/dbg/module.cpp
src/dbg/symbolsourcebase.h
src/gui/Src/Gui/ZehSymbolTable.cpp
src/gui/Src/Gui/ZehSymbolTable.h
src/gui/Src/Utils/Configuration.cpp

This PR fixes issue #1997 and also fixes the symbol table comparator for descending sort. Previously the comparator wasn't a strict weak ordering, and it failed the msvc debug checks on equal keys.
This PR changes the bridge API for DbgGetSymbolInfo by adding a DWORD ordinal member to the SYMBOLINFO struct. I'm not sure how desirable this is, it would at least require the pluginsdk to be updated as well (maybe there is a more compatible way to pass the ordinal that I haven't figured out).

Add DLL ordinal to symbol table and fix symbol table comparator

---

src/dbg/commands/cmd-undocumented.cpp
src/zydis_wrapper/zydis_wrapper.cpp

This PR fixes issue #2047 .  The ZydisOperandAction was used incorrectly in Zydis::RegInfo which is used by the RegistersView on the GUI side, and also by the undocumented zydis command (however there only a few edge cases were wrong due to different usage).

ZYDIS: Use ZydisOperandAction as an enum instead of a flag

---

src/dbg/watch.cpp

Floating point watch points seem to have been broken for a while, this PR fixes the missing enum in the DBG-side evaluation of such  watch points.
To test this simply add a floating point watch point at the top of the stack:
AddWatch dword(rsp),float
And also follow the stack in a Dump using float display. The watch and the dump values should always match when the watch's UI is updated.

DBG: fix getting raw int value for float typed watch points

---

src/gui/Src/Gui/CPUInfoBox.cpp
src/gui/Src/Gui/XrefBrowseDialog.cpp

* With old comparator, items {1, 2} and {2, 1} were "less" then each other. This will cause them to sort randomly.

Fixed incorrect comparator used in sorting xrefs

---

src/dbg/_global.cpp

It was printing pointer to stack instead of size

Fixed incorrect error message when memory could not be allocated

---

src/gui/Src/Gui/EditFloatRegister.cpp
src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/WatchView.cpp
src/gui/Src/Utils/StringUtil.cpp
src/gui/Src/Utils/StringUtil.h

This PR fixes issue #1816 .
QString::number doesn't support displaying -0.0, so I converted all usages on the GUI to ToFloatString/ToDoubleString. This fixes the floating point display in the MMX/XMM/YMM editor, in the registers view in SIMD float/double mode, and in the Watch window for floating point type watchpoints.
To support this all void* buffer based StringUtil functions are now const correct, and ToFloatString/ToDoubleString got an optional precision parameter, which is set to the previously used value by default.
One noteable change is that ToDoubleString has 15 digits of precision by default, while QString::number only had 6 (the same as ToFloatString has). With the new precision parameter we can set it back to 6 if necessary, but I think the more precision the better 😃
The …

GUI: fix negative zero floating point display

---

src/dbg/commands/cmd-searching.cpp

This PR fixes the crash in issue #2015.
When `cbInstrYara` was called with a single argument (argc==2) it tried to dereference the second argument after the end of the argv array in a few cases to try to find the module that should be used.
This PR restores the intended/documented behavior when used with a single value, that
`base = sel.start`, size is the region size from `MemFindBaseAddr(addr, &size)`, and the module name is resolved with `ModNameFromAddr`.

DBG: fix yara crash when used with a single argument

---

src/dbg/_scriptapi_symbol.cpp

* Such symbols have "" instead of nullptr in SYMBOLINFO.undecoratedSymbol
* This fix greatly improves Snowman's decompiled results, example: comctl32!ListBox_SetCurSelHandler

Fixed Symbol::GetList() for symbols without undecorated name

---

src/dbg/module.cpp

This PR fixes #2065.
`ReadDebugDirectory` could scan past the end of the mapped PE file if the Debug Directory's size is bogus, e.g. 0xfffff000. This PR adds a check for `debugDir + debugDirSize` not pointing out of the mapped image.
There is also an additional check that detects unsigned integer wraparounds, in this case with size 0xfffff000 the calculation would wrap around to 4096 bytes before debugDir which would be inside the mapped area.

DBG: Fix mapped area overrun in ReadDebugDirectory

---

src/dbg/module.cpp

Ref: #2105 #2065
This is essentially the same as PR #2069, but applied to all PE directories. This fixes #2105 (at least the first attachment, likely both) without a need for `try/except` (though keeping the wrapper added in 7d53b1a doesn't hurt).

DBG: more robust validation of PE directory sizes

---

src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/RegistersView.h

I was looking at #2002 and I took a shot at implementing it. This is what I have so far. It covers movements for the general purpose registers and flags for x32. I figured since the positions of the registers in the register view seem to be hardcoded and unlikely to change it'd be best to just hardcode the arrow movements as well instead of a more complicated solution. Not sure if that's a bit weird though so I was wondering what people thought about it before I proceeded further. If you have no major problems with that and think it's an ok approach I can roll it out for the rest of the registers.

Register view arrow keys

---

src/dbg/module.cpp

if (IMAGE_EXPORT_DIRECTORY.AddressOfFunctions[i] == 0), the export name after "i" would be wrong. similar to issue https://github.com/x64dbg/x64dbg/issues/2139. here is the fix.

Fix export name parsing

---

src/dbg/module.cpp

There is another bug that is not fixed in PR https://github.com/x64dbg/x64dbg/pull/2158. 
Info.exports.size() may be less than exportDir->NumberOfFunctions, so the export name is not displayed correctly when addressOfNameOrdinals[i] is greater than or equal to Info.exports.size().
Look into the issue https://github.com/x64dbg/x64dbg/issues/2139, view the last export symbol of libeay321.dll in x64dbg(ordinal 4789), the correct one should be "ossl_safe_getenv".

Fix export name is not parsed correctly

---

src/gui/Src/BasicView/ShortcutEdit.cpp

Like discussed in the issue [#2176](https://github.com/x64dbg/x64dbg/issues/2176) the Qt keys are not bitflags so we can't do binary logic. Moreover the TAB key changes focus so it shouldn't be even possibile to have it bound to some action if said binding is set through the UI (same reasoning applies to BACKTAB).

Removed backtab key substitution

---

src/gui/Src/Gui/AppearanceDialog.cpp
src/gui/Src/Gui/CPUSideBar.cpp
src/gui/Src/Gui/CPUSideBar.h
src/gui/Src/Utils/Configuration.cpp

This resolves #811.
Forward and backwards jumps use cyan and orange respectively.
Cyan/orange were chosen over red/green to aid red/green colorblindness as well as any positive/negative connotations based on green/red.
All executing jumps still show as red regardless of direction.
Existing configurations will use their defined color for forwards, and orange for backwards.

GUI: #811 - Sidebar jump direction color differentiation.

---

src/dbg/module.cpp
src/dbg/module.h
src/dbg/stackinfo.cpp

`StackWalk64` with `SymFunctionTableAccess` would be incorrect if `SymInitializeW` & `SymLoadModuleEx` is not called for specific module.
According to my research, `SymLoadModuleEx` would read UNWIND_INFO resident in PE file, without which unwinding wouble fail.  Using UNWIND_INFO ,  debugger such as Windbg can do stacktrace even without pdb. UNWIND_INFO is located at `pNTHeader->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXCEPTION]`
Indeed Unwinding is quite a complex affair including function prologue and epilogue... emh. Refer to the following: 
https://github.com/dotnet/coreclr/blob/master/src/unwinder/amd64/dbs_stack_x64.cpp

fix stack trace in x64

---

src/gui/Src/Gui/AppearanceDialog.ui

This resolves #1999 per @mrexodia comment to open PR for adding a label.
This does not address @twifty's request to "would it be possible to resize the button bar according to the font size. Currently they are just too small. One must be very careful not to click the wrong one.".
Added label to bottom of appearance dialog font tab that explains that "*" denotes setting that requires app restart to take effect.
Label is word wrapped and vertical expanding to help with larger font choices.
Only English locale.
Example:

GUI: #1999 - Added restart required label for system font change

---

src/dbg/analysis/advancedanalysis.cpp

This PR fixes issue #2169 .
Added range checks to analyzeFunction, so it stops when reaching the end of the memory range regardless whether it is data byte, an incomplete instruction or a complete instruction right at the end of the range.
Added range checks to writeDataXrefs for operands that are bigger than one byte, and simplified handling multi-byte operands.

DBG: fix advanced analysis crash

---

src/dbg/debugger.cpp

On terminating an attached process after terminating a created process will result in invalid handle exception. This is due to calling CloseHandle on the previous process's hProcessToken.

DBG: fix invalid handle exception on terminating attach after run

---

src/dbg/debugger.cpp
src/dbg/debugger_cookie.h

This PR fixes issue #2164 .
CookieQuery will first try querying the process cookie when creating a process or attaching, using NtQueryInformationProcess, which should succeed on Windows >= 8. If it does not succeed we add the breakpoints to NtQueryInformationProcess only when attaching.

Fix process cookie on attach

---

src/gui/Src/Gui/CallStackView.cpp

This PR fixes GUI issue in #2180 .
Moved the MenuBuilder::BuildCallback from the "Follow To" context menu to the "Follow From" context menu.

GUI: fix Follow From context menu in CallStackView

---

src/dbg/stackinfo.cpp

Fixes #2254.
The function end address in the `RUNTIME_FUNCTION` struct points to one byte beyond the last instruction of the function (like STL ranges).
The current lookup method results in incorrect stack frames on entry into a function "B" that starts immediately after another function "A", resulting in function A's unwind metadata incorrectly getting used to unwind the stack instead of function B's.
**Existing behavior:**
Find `func` where:
`func.BeginAddress <= rva <= func.EndAddress`
**New behavior:**
Find `func` where:
`func.BeginAddress <= rva < func.EndAddress`

DBG: Fix function boundary computation when getting x64 stack frames

---

README.md

The TitanEngine repository has moved from BitBucket to Github. This PR is to update it so others can quickly get to the most up to date codebase.

Updated link to TitanEngine

---

src/gui/Src/Gui/AssembleDialog.cpp
src/gui/Src/Gui/CPUDisassembly.cpp

BUG: When assembling an instruction, if we copy and paste an instruction from somewhere with whitspaces [ \r\n] it results in invalid parsing in asmjit engine selected and throws an error as "Error writing to memory".
SCENARIO: Copy and pacste an instruction from a text editor with a newline prefix to the assemble dialog and try to assemble.
If there is newline in the prefix the validation don't even care about the expression after the newline prefix.

GUI: Sanitizing input expression before assemble.

---

src/bridge/bridgemain.h
src/gui/Src/Disassembler/QBeaEngine.cpp
src/gui/Src/Disassembler/QBeaEngine.h
src/gui/Src/Disassembler/ZydisTokenizer.cpp
src/gui/Src/Gui/CPUInfoBox.cpp
src/gui/Src/Gui/CPUInfoBox.h
src/gui/Src/Gui/RegistersView.cpp
src/gui/Src/Gui/RegistersView.h
src/gui/Src/Tracer/TraceBrowser.cpp
src/gui/Src/Tracer/TraceBrowser.h
src/gui/Src/Tracer/TraceFileReader.cpp
src/gui/Src/Utils/StringUtil.cpp
src/gui/Src/Utils/StringUtil.h
src/zydis_wrapper/zydis_wrapper.cpp
src/zydis_wrapper/zydis_wrapper.h

Support viewing XMM/YMM registers in infobox and XMM data in disassembly
The user now has to select to display ST(X), x87rX or MMX.

Support viewing XMM/YMM registers in infobox and XMM data in disassembly

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/commands/cmd-gui.cpp
src/dbg/commands/cmd-gui.h
src/dbg/x64dbg.cpp
src/gui/Src/Bridge/Bridge.cpp
src/gui/Src/Bridge/Bridge.h
src/gui/Src/Gui/MainWindow.cpp

These changes allow to show the "References" tab either via plugin or using new command `showref`

Programatic way to show "References" tab

---

src/dbg/breakpoint.cpp

Fixes: Memory breakpoints summary always shows type as access for all types.
@BreakPointView.

DBG: Added memory breakpoint's types in BpToBridge conversion.

---

src/dbg/debugger_tracing.h
src/dbg/expressionparser.cpp

fix "Trace already active" when start tracing after "ticnd ())"
"ticnd []]" is now invalid

fix "Trace already active" after "ticnd ())"

---

src/gui/Src/Gui/CPUDump.cpp
src/gui/Src/Gui/CPUDump.h
src/gui/Src/Gui/CPUMultiDump.cpp
src/gui/Src/Utils/BackgroundFlickerThread.cpp
src/gui/Src/Utils/BackgroundFlickerThread.h
src/gui/x64dbg.pro

This pull request implements idea covered in #1794 issue. Now it is easier (at least in my opinion) to focus on the dump widget, instead of the disassembly widget which doesn't change when following some addresses

Flashing background instead of border when following reference in dump

---

src/gui/Src/BasicView/Disassembly.cpp

When I used x64dbg I found this incorrect, it should follow source operand. Most often destination operand doesn't have anything meaningful.

Follow source operand

---

src/dbg/disasm_helper.cpp
src/dbg/stringutils.cpp
src/dbg/stringutils.h

String searching is always a headache for most x64dbg users. Most users need to find a plugin or special version for their language, and almost none of them are free and open source. I try to fix that by improving the algorithm to work with all people at the cost of some more useless strings being found, which is acceptable for me.
The algorithm used here is very simple: it converts to and from Unicode, and checks whether the original string is recovered after round-trip conversion without errors. It works for me, and users in other languages are encouraged to test it.

Updated string searching algorithm to support string in any language

---

src/gui/Src/Tracer/TraceWidget.cpp

After the recent addition of TraceWidget.cpp the project doesn't compile using VS2015 compiler with following error:
```functional:497: error: C2719: '_Func': formal parameter with requested alignment of 16 won't be aligned```
`x64dbg\src\gui\Src\Tracer\TraceWidget.cpp:268: see reference to function template instantiation "std::function<size_t (ZydisRegister)>::function<TraceWidget::updateInfobox::<lambda_15bf0c2c58dce742746d406f455e8824>,unsigned long,void>(_Fx)" being compiled
with
[
_Fx=TraceWidget::updateInfobox::<lambda_15bf0c2c58dce742746d406f455e8824>
]
`
I know that the main target for the project is VS2013, however I think the commit doesn't change anything in the program behavior and now it builds using VS2015 without errors.

Fixed compilation error for VS2015

---

src/gui/Src/Disassembler/QBeaEngine.cpp
src/zydis_wrapper/zydis_wrapper.cpp

Firstly, the indicators in CPUSideBar aren't shown for LOOPxx instructions.
Also, back in the days when you selected LOOPxx instruction, you could spot the hint like "Jump is taken" or "Jump is not taken" in the CPUInfoBox. I believe this was deleted by this commit https://github.com/x64dbg/x64dbg/commit/6348cb5728f53f51c96c272423153dd3476bc21e after changes in `CPUInfoBox::disasmSelectionChanged` because it is still present in my April snapshot. However, it was working incorrectly. This is, because the LOOP instruction **firstly decrements** the ECX, then checks if it's != 0. I will try to explain it using images.
ECX = 0, "Jump is not taken" in the info box
However... the jump is in fact taken, ECX = 0xFFFFFFFF
Now when the ECX = 1, "Jump is taken" in the info box
However... the jump is …

Changes connected to LOOPxx instructions

---

bin/themes/Dark/style.ini
src/gui/Src/Gui/MainWindow.cpp

It doesn't need to set font when switching to dark theme, and the font used in dark theme shouldn't override the user setting.

Don't override user font when using dark theme (#2422 #2426)

---

src/gui/Src/BasicView/SearchListView.cpp
src/gui/Src/Gui/CPUDump.cpp

It seems that at the moment the FlickerThread and BackgroundFlickerThread objects are never deleted (despite fact that they are allocated on the heap using "new" operator)

Fixed memory leak; properly clean QThread after it finishes

---

src/gui/Src/BasicView/HistoryLineEdit.cpp
src/gui/Src/BasicView/HistoryLineEdit.h
src/gui/Src/Gui/CommandLineEdit.cpp
src/gui/Src/Utils/Configuration.cpp

This improves #2184 by adding a setting to disable the behaviour

Fetch mCmdHistory on an empty mCmdLineEdit and able to disable it

---

src/gui/Src/Gui/BreakpointMenu.cpp

Replacement candidates used to show "Slot X (Free)" before sometimes when there are disabled hardware breakpoints. Fix it and change the placeholder to "Unknown" since it's logically invalid to display the menu when there's a free slot.

Fix hardware breakpoint replacement slot display

---

src/dbg/stackinfo.cpp

In some cases, the call stack information for a 64-bit process cannot be obtained correctly.
reference: https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/ns-dbghelp-stackframe
AddrFrame
An ADDRESS64 structure that specifies the frame pointer.
x86:  The frame pointer is EBP.
Intel Itanium:  There is no frame pointer, but AddrBStore is used.
x64:  The frame pointer is RBP or RDI. This value is not always used.

In some cases, the call stack information for a 64-bit process cannot be obtained correctly.

---

src/dbg/commands/cmd-watch-control.cpp
src/dbg/commands/cmd-watch-control.h
src/dbg/watch.cpp
src/dbg/watch.h
src/dbg/x64dbg.cpp
src/gui/Src/Gui/WatchView.cpp
src/gui/Src/Gui/WatchView.h

-Added new command `SetWatchType`, not sure if it is necessary but I think it's more clean this way
-Added possibility to change watch type from context menu (lack of possibility to change the watch type from gui was reported in #2309)

GUI: Possibility to change watch type using GUI (context menu)

---

src/gui/Src/Gui/WatchView.cpp

Now the input box contains current watch expression, instead of showing empty input box.

GUI: Improved editing expressions in watch view #2308

---

src/dbg/value.cpp

This fixes commands such as `_ZF=1` where ZF is already set to 1 by checking whether the bit is already set.

Fix flag setting when flag is already set

---

src/dbg/commands/cmd-user-database.cpp

It's common to set both label and comment for functions and bookmarks. It's useful to show both of them. Function size is added as well.

Display both labels and comments for functions and bookmarks list

---

src/dbg/watch.cpp
src/gui/Src/Gui/WatchView.cpp
src/gui/Src/Gui/WatchView.h

-Added column enum to WatchView
-Added current type to `SetWatchExpression` executed from `editWatchSlot`, this is because otherwise if no type is specified this resets the watch type back to `uint`
-Added "force refresh" feature. Without this change, after you edit watch expression, the value of this particular watch is always "0" until you refresh it by for example stepping to next instruction.

Changes related to WatchView

---

src/gui/Src/Gui/MainWindow.cpp

The favourite toolbar is now placed in main toolbar, not at (0,0) when first used.

Fix transparent favourite toolbar hovering over the File menu

---

src/dbg/_dbgfunctions.cpp
src/dbg/_dbgfunctions.h
src/dbg/stackinfo.cpp
src/dbg/stackinfo.h
src/gui/Src/Gui/CallStackView.cpp
src/gui/Src/Gui/CallStackView.h
src/gui/Src/Utils/Configuration.cpp

-Added new function (GetCallStackByThread)
-Change the call stack view, it displays call stacks from multiple threads now
Hope it looks better now. Not sure if the internals of that function looks good for you.
Before: 
After:

Improved call stack tab, displaying multiple threads 

---

src/dbg/module.cpp

Use PointerToRawData in debug directory if no RVA is present

---

src/dbg/_exports.cpp
src/dbg/debugger.cpp
src/dbg/debugger.h
src/gui/Src/Gui/SettingsDialog.cpp
src/gui/Src/Gui/SettingsDialog.h
src/gui/Src/Gui/SettingsDialog.ui

This PR overhauls the exceptions tab (currently 'ignored exceptions') with changes to give more control over what happens when a specific exception (or range) is encountered:
Most of the changes were already discussed in #2582. Brief rundown of the major changes:
- Added controls to tell x64dbg when to break (first chance, second chance, or do not break at all).
- Added controls to tell x64dbg whether to pass the exception to the debuggee or not.
- Added 'log exception' checkbox to allow completely silent exceptions that do not show up in the log or status bar.
-  Renamed buttons 'add range' and 'add last' to 'ignore range' and 'ignore last'. The default starting settings for an 'ignored' entry are to break only on the second chance and to let the debuggee handle the exception. Logging is …

Make Exceptions Great Again

---

src/dbg/debugger.cpp
src/gui/Src/Gui/SettingsDialog.cpp
src/gui/Src/Gui/SettingsDialog.h
src/gui/Src/Gui/SettingsDialog.ui

I like the `NtTerminateProcess` breakpoint that can be enabled in the settings, but it has some issues compared to what I'm used to from WinDbg. Consider the following program:
```C++
int main()
{
return TerminateThread(GetCurrentThread(), 0);
}
```
This will bypass the `NtTerminateProcess` breakpoint, since terminating the last thread of a process will also terminate the process (but without invoking `NtTerminateProcess` directly.) A probably more useful example is some other process (task manager or maybe something more malicious) terminating the debuggee process. In cases such as this it is currently not possible to do a proper post mortem to see what caused the debuggee to exit, because the entire GUI state is wiped.
This PR renames the `NtTerminateProcess` breakpoint to simply 'Exit …

Change NtTerminateProcess breakpoint to a generic 'exit breakpoint'

---

src/dbg/debugger.cpp

As requested by @torusrxxx in #2592 (which was already merged when he left the comment).

Clear history before exit breakpoint

---

src/dbg/_plugins.cpp
src/dbg/_plugins.h
src/dbg/expressionfunctions.cpp
src/dbg/expressionfunctions.h
src/dbg/expressionparser.cpp
src/dbg/expressionparser.h
src/dbg/exprfunc.cpp
src/dbg/exprfunc.h
src/dbg/plugin_loader.cpp
src/dbg/plugin_loader.h
src/dbg/stringformat.cpp

Modified the way expression functions are handled, and implemented a few new functions that will be useful when setting conditional breakpoints among other things:
- strstr i.e. `strstr(utf8(addr), "abc")`
- strcmp i.e. `strcmp(utf8(addr), "abc")`
Where both can use utf8() or utf16() to specify what sort of string format is being read from memory.
Example plugin: https://github.com/xenocidewiki/x64dbgplugintest

New system for expression functions

---

src/gui/Src/Gui/CPUInfoBox.cpp
src/gui/Src/Gui/CPUInfoBox.h
src/gui/Src/Gui/CPURegistersView.cpp
src/gui/Src/Gui/EditFloatRegister.cpp
src/gui/Src/Gui/EditFloatRegister.h
src/gui/Src/Tracer/TraceBrowser.cpp
src/gui/Src/Tracer/TraceRegisters.cpp
src/gui/Src/Tracer/TraceRegisters.h
src/gui/Src/Tracer/TraceWidget.cpp

- The content of FPU registers now show in the trace info box as numbers, easing the reverse engineering of floating point code.
- Double click on EIP in trace registers will follow in disassembly, double click on XMM register in trace registers will open the View XMM registers dialog.
- FPU operands in memory will now display in the trace info box.
- Moved Thread ID from "Information" menu to trace info box
- Increase output precision for FPU register in info box
- Hide scrollbars in trace info box

enhance the FPU support for trace info box and trace registers view

---

src/gui/Src/Gui/CallStackView.cpp

I think that in future it could be a good idea to implement sorting via Thread ID, but for now I think disabling is ok, to avoid the possibility of breaking the widget.

GUI: Disabled possibilty to sort content in call stack tab, fixed #2637

---

src/gui/Src/Gui/WordEditDialog.cpp
src/gui/Src/Gui/WordEditDialog.h
src/gui/Src/Utils/StringUtil.h

In the current version of x64dbg the value is always treated as duint, thus for example when modifying the value in 1 byte mode, the signed/unsigned values are converted to duint/int as in the #2665. Also in the current version, the "Signed" field input value will never be less than zero when double clicking the value in dump in signed word/byte mode.
This pull request changes this behavior.

MemoyDump - "modify" dialog fix

---

src/dbg/comment.cpp

Fixed crash mentioned in #2654

DBG: Fixed crash when comment longer than 512 characters

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/commands/cmd-gui.cpp
src/dbg/commands/cmd-gui.h
src/dbg/x64dbg.cpp
src/gui/Src/Bridge/Bridge.cpp
src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/Gui/MemoryMapView.cpp
src/gui/Src/Gui/MemoryMapView.h

-Added new command "symfollow" to follow base address in the symbols tab (not sure if this is good idea)
-Implemented feature suggested in #2515 - added "Follow in symbols" to Memory Map context menu

Added "Follow in Symbols" to the Memory Map context menu

---

src/gui/Src/Gui/SettingsDialog.cpp

What happens: the 'unknown exceptions' filter. which is a special filter that is not supposed to be deletable in settings, can be accidentally deleted. This was reported to me by someone who added an exception filter for `00000000-FFFFFFFF`, but adding any filter that includes 0 in its range will cause this. The result is a broken settings dialog that will stay broken even if x64dbg is restarted, because the invalid list will be persisted in the INI.
Cause of above is an off-by-one error; this PR fixes it.
Related (maybe, the issue is not overly descriptive but it seems to match): closes #2708

Don't delete 'unknown exceptions' filter in settings dialog

---

src/dbg/formatfunctions.cpp

This adds `comment` and `label` to format functions. This can be handy to log automatic comments or labels such as symbol names or comments that are automatically identified by x64dbg.
Example:
```
log "{comment@eip}"
log "{label@eax}"
```
inspired by #2510

DBG: add comment and label format functions

---

src/dbg/debugger_tracing.h

If there is only log/command text but no condition, then logCondition or cmdCondition would not be NULL and the default value provided in `return logCondition ? logCondition->Evaluate() : 0;` would not be used.

set default log and command conditions

---

src/gui/Src/BasicView/AbstractTableView.cpp
src/gui/Src/BasicView/HexDump.cpp

The built-in "enter" shortcut of the CPUStack widget only works with Qt::Key_Return, and doesn't work with Qt::Key_Enter, both should work.

Fix the enter key on the keypad not working in CPUStack widget

---

src/dbg/stringformat.cpp
src/gui/Src/Gui/CPUDump.cpp

Add string format to print floating point number pointer:
The user can print a float number with format `{f:pointer}` or double number with format `{F:pointer}`
Add the UI to modify floating point number in dump:
The user can edit the floating point number in dump by double-clicking.

Eenhanced floating point support

---

src/gui/Src/Gui/AssembleDialog.cpp
src/gui/Src/Gui/AssembleDialog.ui

Just a small code change to set the OpCode at the AssembleDialog to a newline. In my opinion it looks a bit squeezed now.
Thanks to torusrxxx for implementing this feature, it's really neat.
before:
after:

AssembleDialog - OpCode to newline

---

src/gui/Src/BasicView/SearchListView.cpp

Hi, some users like me can't use (non-ascii) characters like ç, ğ, ş, ö in some text boxes. I think this patch fixes that.

Fix for printable characters

---

src/gui/Src/main.cpp

[#2876](https://github.com/x64dbg/x64dbg/issues/2876)

Using SetProcessDpiAwarenessContext instead of QTAPI on Win10 above 1703

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/_plugins.cpp
src/dbg/_plugins.h
src/dbg/console.cpp
src/dbg/console.h
src/gui/Src/Bridge/Bridge.cpp
src/gui/Src/Bridge/Bridge.h
src/gui/Src/Gui/LogView.cpp
src/gui/Src/Gui/LogView.h

Allow developers to add HTML to the displayed log window, for instance to highlight certain parts of the log messages.
```
Log.msg("<span style="color:red;">This message will be colored</span>);
```
Original PR;
> 
> Allow developers to add color styling to the displayed log window, to highlight certain parts of the messages.
> 
> ```
> Log.msg("[color@red] This message will be colored. [stopcolor]")
> ```
> 
> ![2022-02-12-18_36-NKtTQNO8JA](https://user-images.githubusercontent.com/1904543/153702017-c0e6ed30-b16c-4af3-b282-a204b21fb8cb.png)
> 
> 
> -----
> 
> This is probably not the syntax we would ideally want, but we cannot directly enter HTML into the log due to the escaping in LogView.cpp on line 263:
> ```   
> msgUtf16 = msgUtf16.toHtmlEscaped();
> ```
> 
> Additionally, we cannot …

Extra Log method for HTML

---

src/gui/Src/BasicView/ReferenceView.cpp
src/gui/Src/BasicView/SearchListView.cpp

issue #2589
Also I fixed array out of bounds assertion failure at this line:
https://github.com/x64dbg/x64dbg/blob/56eef9553ec2d45f45b5036078be9cff013e64df/src/gui/Src/BasicView/SearchListView.cpp#L380
Return value of `QKeyEvent::text()` can be empty string for modifier key press event (Ctrl, Shift, ...)

Add ability to set breakpoints on multiple selected lines in the References tab

---

src/launcher/x64dbg_launcher.cpp

The debugger exe file (x32dbg.exe, x64dbg.exe) can be renamed but we can't select it from the launcher dialog. This commit updates the filter text.

Update filter text in the launcher dialog

---

src/dbg/symcache.cpp

Hello,
This patch fix a regression where undecorated label wasn't shown in assembly view when it comes from exported symbols.
Fix #2726.
Regards,
Owerosu

Fix undecorated label display when it comes from exported symbols.

---

src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/Utils/Configuration.cpp

fix #2097.
The user can always reinstall x64dbg if there is a problem with topmost
This pull request also fixes the main window being shown in the default position for a brief moment before being moved to its remembered position on start up.

remember window topmost configuration

---

.github/workflows/gitee.yml

Upgrade actions/checkout package from v2 to v3.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Signed-off-by: Austin Vazquez <macedonv@amazon.com>

Upgrade actions/checkout package to v3

---

src/dbg/symbolundecorator.h

To make the output more similar to other tools such as WinDbg.
For example:
x64dbg:
`public: class _bstr_t & __ptr64 __cdecl _bstr_t::operator=(class _bstr_t const & __ptr64) __ptr64`
WinDbg:
`public: class _bstr_t & __cdecl _bstr_t::operator=(class _bstr_t const &)`
I got the value `0x20800` by looking at the assembly of `get_undecoratedName` in msdia140, which calls `get_undecoratedNameEx` with these flags.

Use common undecorate flags

---

src/dbg/commands/cmd-thread-control.cpp
src/dbg/debugger.cpp

There's still a lot of improvements that could be made, where the PID/TID is always hexadecimal, but this was the worst one IMO.

Fix and improve "Show PID/TID in HEX" feature

---

src/dbg/_exports.cpp
src/dbg/debugger.cpp
src/dbg/debugger.h
src/gui/Src/Gui/SettingsDialog.cpp
src/gui/Src/Gui/SettingsDialog.h
src/gui/Src/Gui/SettingsDialog.ui

Closes #2885
Closes #2946
>**Feature type**
>
>Quality of life
>
>**Describe the feature**
>
>When debugging different versions of a program, it could be you lose track of which version you looking at. Showing the file path in the window title like IDA does could quickly help there.
Under the GUI settings we find the new option `Set Long Window Path`. If this is enabled, instead of the normal window title (showing current thread and other parameters) the absolute path to the debugge is shown instead.
When we attach to a target we can now choose between the two views shown below, by toggling the option:

New Option to Show Path of Debuggee in Window Title

---

src/dbg/debugger.cpp
src/dbg/thread.cpp
src/gui/Src/Gui/SettingsDialog.cpp
src/gui/Src/Gui/SettingsDialog.h
src/gui/Src/Gui/SettingsDialog.ui

My arguments for this change:
- this gets spammed a lot in some apps during startup or runtime, forcing you to keep pressing Go or disable first-chance exception breaking altogether (it doesn't look like there's another way to just filter out that one)
- it's supposed to be just an information for the debugger itself rather than a real exception
- it shouldn't be missed if needed since the operation is logged in the debug log
In case of the game I'm debugging this changed from having to press Go 30 times on startup and regularly during runtime, to literally nothing (because all these random exceptions I was getting were apparently just setting thread name on the debugger). 
So I think it would be a nice QoL change. I *think* most people shouldn't really need an exception like this, if …

Don't break on SetThreadName exception

---

src/gui/Src/Gui/AppearanceDialog.ui
src/gui/Src/Gui/CallStackView.cpp
src/gui/Src/Utils/Configuration.cpp

It is possible to press F2 to add a breakpoint directly in call stack view, but the visual indicator is missing.
Added a default color for hardware breakpoints as well.

Add breakpoint background color in call stack view

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/_exports.cpp
src/dbg/_scriptapi_symbol.cpp
src/dbg/symbolsourcebase.h

Mainly to overcome the restrictive `MAX_LABEL_SIZE` limit, and to be a able to get heavily templated symbols.

Add the DbgGetSymbolInfoAt API

---

src/gui/Src/Gui/AppearanceDialog.cpp
src/gui/Src/Gui/AppearanceDialog.h
src/gui/Src/Gui/LogView.cpp
src/gui/Src/Gui/ScriptView.cpp
src/gui/Src/Gui/SystemBreakpointScriptDialog.cpp
src/gui/Src/Utils/Configuration.cpp

Fine tuned the style of example text when using the transparent background color.
Qt cannot open text file with Chinese characters in file name??? Add error messages (releases from 2021 cannot open it either)

Set proper default style for example text in appearance dialog

---

src/gui/Src/Tracer/TraceFileReader.cpp

Here, I made a GIF of the exporting process (the columns are current row, time taken to write 4096 rows, ram usage).
You can see how it suddenly slows down after the counter reaches something around 1 million rows. It quickly eats up all "cachable" 2048 pages and then just spends most of the time trying to find the oldest one to evict. With searching the situation is the same except the ram usage goes up to 1200MB.

Fix trace export and search being extremely slow on large trace files

---

src/gui/Src/Gui/CPUStack.cpp
src/gui/Src/Gui/CPUStack.h

It would be nice to be able to copy the second (data) column from the stack view.
I found several ways to do it which are not very intuitive or simple (copy the entire row with Ctrl-C and then somehow extract the needed column text, open the Modify dialog and copy the value from there, choose the "Copy data" tab of the Edit dialog and select "C-Style DWord" or something, copy raw bytes with Shift-C and then somehow reverse the endianness and remove spaces).
Besides, almost all other tables allow you to copy each column contents separately.
The added actions also can copy several rows of the selected column for no particular reason (the disassembly table behaves similarly).

Add actions to copy DWord/QWord and Comments in the Stack view

---

src/dbg/_global.cpp
src/dbg/_global.h
src/dbg/commands/cmd-debug-control.cpp
src/dbg/debugger.cpp
src/dbg/debugger.h

`ResolveShortcut` now optionally fills resolved arguments which are passed onto the command line.
Closes #3110

Resolve command line arguments from shortcuts

---

src/dbg/module.cpp
src/dbg/module.h

- Fixed some bugs in virtualmod: loadedSize was never set + the mapped data would be destroyed prematurely, causing a crash after initially parsing the module.
- Use raw RVA instead of rebasing when reading module information from memory.
- Set MappedAsImage = true when calling RtlImageDirectoryEntryToData on in-memory sections, as expected.
- This works out of the box for some basic stuff (e.g. symbols, imports, exports are loaded properly) but for full functionality a fix is needed in MemoryModule (see https://github.com/ynwarcs/MemoryModule/commit/10250ad4b7ee464579dfb13605427bad1626cbd9). TL;DR: VirtualSize field in the section header is not properly set by MemoryModule, leading to sections not being parsed properly during page sorting, leading to an error spam and some other annoying …

Support for MemoryModule recognition and debugging via virtualmod.

---

README.md

Hi there,
I'm trying to get into contributing to open source projects and as I'm interested in reverse engineering I thought I might give it a go with this project.
When I was reading through `README.md` and clicked on the "good first issues" link it showed an empty list, which left me a bit puzzled. I guess the reason is that this hyperlink uses the "Easy" label to filter:
Luckily I found a link that works while reading through `CONTRIBUTING.md` and thought I might start off with this simple PR. Now the same link is used in `README.md` and it should apply the correct filter to anyone who clicks it.
I haven't compiled x64dbg yet as described in the list, I hope it is still fine to already open this PR. I'll give the rest of the things in the document a go as well and tried to follow the …

Use same link as found in CONTRIBUTING.md

---

src/dbg/commands/cmd-general-purpose.cpp
src/dbg/commands/cmd-general-purpose.h
src/dbg/value.cpp
src/dbg/x64dbg.cpp

fix #3087.
MOVDQU currently only works with XMM registers. VMOVUPS could be added to modify YMM and ZMM registers. The goal is to match the behaviour of processor instruction, so that users don't have to read the x64dbg manual because they already know SSE and AVX.

Add movups/movupd/movdqu commands to access XMM registers

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/expressionfunctions.cpp
src/dbg/exprfunc.cpp
src/dbg/exprfunc.h
src/gui/Src/Bridge/Bridge.cpp

The new expression function returns 1 if x64dbg is focused. It can be used in a conditional breakpoint so that you're able to break when you're playing the game but not when you're looking at CPU.
It doesn't return 1 when a plugin window is focused. Currently there's also no way to break when the debuggee is focused after 1 seconds so that it doesn't break just when it is focused.
I also evaluated approach of a system variable that changes when x64dbg is focused, but I'm concerned that event filter may impact GUI responsiveness too much. (some old games with DirectInput lock up the entire system with low-level keyboard & mouse hooks that you either don't put a breakpoint there, or disable these hooks and can't play it)

add isdebuggerfocused() to determine if x64dbg is focused

---

src/dbg/WinInet-Downloader/downslib.cpp
src/dbg/symbolinfo.cpp

Hello, this is my first time contributing. 
I was building my own symbol cache server and I noticed that x64dbg did not support/accept gzip encoding. I thought it would be good to take some time to add support for this as it dramatically improves performance when downloading PDB's from symbol servers that support this. 
I also increased the chunk size slightly to improve performance by trying to reduce the number of iterations it takes to write to the PDB.

Adding gzip decompression to downlibs

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/x64dbg.cpp
src/gui/Src/Bridge/Bridge.cpp
src/gui/Src/Bridge/Bridge.h
src/gui/Src/Gui/LogView.cpp
src/gui/Src/Gui/LogView.h
src/gui/Src/Utils/MiscUtil.cpp
src/gui/Src/Utils/StringUtil.cpp
src/gui/Src/Utils/StringUtil.h

Commands are designed as proposed in https://github.com/x64dbg/x64dbg/issues/2961#issuecomment-1292878777
The only different is for `logredir [arg1]`: ~~if arg1 is not provided, it'll fail just as providing the default value in the log redirect dialog, to be compatible with the dialog behaviour.~~ arg1 is now mandatory.
Let me know if anything needs to be changed (such as the command name), this is my first time contributing.

Add Commands: LogSave, LogRedirect, LogRedirectStop

---

src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/main.cpp

When I place the program in a directory whose path contains an uneven number of opening and closing parentheses (like "C:/exa(mple" or "C:/e(x)am(ple"), images referenced in the css file do not load properly (and the whole file gets messed up during parsing). I guess the right way would be to escape the paths with backslashes at runtime, but then the url has to be parsed properly, and parsing is hard, who knows what might happen, etc. On the other hand, simple quoting is safe, and because `(` and `)` (as well as `\`) are not valid path characters in Windows, you can't escape from a quoted string.

Quote image paths in the Dark theme stylesheet

---

src/dbg/commands/cmd-gui.cpp

Fixes #3113 and #1596.
Fixes an issue with the "Follow DWORD/QWORD in Current Dump" commmand, as well as the "Go to..." expression box when a dump view is detached. It's not the most elegant but it's not terrible either.
If nativeTitle is ever changed [here](https://github.com/x64dbg/x64dbg/blob/6a970e657dc2279c9d2f584dc56cea14a2ba3e2f/src/gui/Src/Gui/CPUMultiDump.cpp#L30) this fix will break. The current user set dump view name does not affect this, nor does any language changes.

Set dump index from ACTIVEVIEW

---

src/gui/Src/Disassembler/ZydisTokenizer.cpp
src/gui/Src/Disassembler/ZydisTokenizer.h
src/gui/Src/Gui/DisassemblerGraphView.cpp
src/gui/Src/Gui/DisassemblerGraphView.h

Last time I forgot that different sub-registers (like rax, eax, ax, al) should be highlighted as well.
Unfortunately, it gets a bit awkward because we have to compare Zydis tokens and then apply changes to rich text. And these rich texts and tokens are not synced (rich text additionally has RVA and comments). Maybe the cleanest solution would be to store RVA and comments separately, and then, when needed, regenerate rich text from the token array and prepend/append the rest. But that would cause a lot of unnecessary object creation on every highlight change.
I've removed the duplicate rich text since the colors can be extracted directly from the tokens. At least the way they are used now.

In Graph mode, also apply highlighting to different sizes of the same register

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/expressionfunctions.cpp
src/dbg/exprfunc.cpp
src/dbg/exprfunc.h
src/gui/Src/Bridge/Bridge.cpp

isdebuggeefocused() is added, in my opinion more useful.
It seems the best way to do it is just GetForegroundWindow().

Add isdebuggeefocused, and optimized isdebuggerfocused

---

src/gui/Src/BasicView/Disassembly.cpp
src/gui/Src/BasicView/Disassembly.h
src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/CustomizeMenuDialog.cpp
src/gui/Src/Tracer/TraceBrowser.cpp
src/gui/Src/Utils/Configuration.cpp

The hidden by default mnemonic brief column helps keep comments column clean while showing mnemonic brief. It also remembers mnemonic brief settings.

Added mnemonic brief column and keeps mnemonic brief configuration

---

src/gui/Src/BasicView/AbstractStdTable.cpp
src/gui/Src/BasicView/SearchListView.cpp

Related issue: #2438 
-CTRL + C functions properly in SearchListView
-CTRL + A when search box is empty selects all rows in table (if allowed) 
-SHIFT + HOME/END when search box is empty selects rows from table (if allowed)
-ESC clears the filter rather than just the Search edit line

CTRL + C functionality in AbstractStdTable/SearchListView

---

src/gui/Src/Gui/RegistersView.cpp

Sometimes programs work with eflags directly (like checking bit 8 to see if the trap flag is set).
In such moments it's nice to have a list of all the flags with their respective bits to quickly understand which flag it is or is not.
Currently, even though the bit numbers are shown in tooltips, the registers themselves aren't sorted in any way, so it takes some time to find the right flag (if you don't remember them exactly).

Show a tooltip with a sorted list of flags in the Register View

---

src/dbg/analysis/advancedanalysis.cpp
src/dbg/analysis/recursiveanalysis.cpp
src/dbg/exception.cpp
src/dbg/handles.cpp
src/dbg/memory.cpp
src/dbg/stackinfo.cpp
src/dbg/types.cpp
src/dbg/xrefs.cpp

I am sure, that not all fixes will be needed, because there are cases when count elements does not exceed 3 for avg user x64dbg.

Using reserve and unordered_map for optimize inserts

---

src/gui/Src/BasicView/SearchListView.cpp

Was blocking Esc from closing Attach window.
Bug I introduced in #3183.

Pass Escape key event if search text is empty

---

src/dbg/WinInet-Downloader/downslib.cpp
src/dbg/disasm_helper.cpp
src/dbg/pdbdiafile.cpp

@mrexodia hi
`new` operator has failed to alloc memory, exception `std::bad_alloc()` is thrown, following to C++ standard (not C).
Сhecking for zero is pointless.

Fixed catch exception std::bad_alloc and close handle hFile if downslib::inetopen

---

src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/CPUDump.cpp
src/gui/Src/Gui/CPUStack.cpp
src/gui/Src/Gui/HexEditDialog.cpp
src/gui/Src/Gui/MemoryMapView.cpp

Removes the "Keep Size" checkbox from the following dialogs. It's nonsensical having them here nor were they doing anything.
- CPUDisassembly->Find Pattern
- CPUDump->Find Pattern
- CPUStack->Find Pattern

Hide Keep Size QCheckBox from all but Binary Edit

---

src/gui/Src/Gui/SymbolView.cpp
src/gui/Src/Gui/SymbolView.h

Many actions in the debugger (like toggling a breakpoint with F2) force all the views to update. That includes the Symbols log. On each update, its font and stylesheet settings are refreshed. Depending on how much text is in the log, that causes serious slowdown to the whole program (e.g. there may be several second delay just to put a single breakpoint).
I don't know precisely how, but it seems to be dependent on the currently selected fonts (maybe non-default ones cause this or something).
**Steps to reproduce**
1. Download the latest snapshot ([snapshot_2023-09-21_00-53.zip](https://github.com/x64dbg/x64dbg/releases/latest))
2. Start & exit `x64dbg.exe`
3. Open `x64dbg.ini` and replace `[Fonts]` with (set some other monospaced font if this one is not present):
```
[Fonts] …
```

SymbolView: Don't update fonts on each 'repaintTableView' event

---

src/dbg/commandparser.cpp

Solves #3210 .
I'm not sure if this is actually an optimal fix. It had seemed that the issue was being caused by escaped double quotes:
`init \\desktop-name\Network\test.exe`
This worked fine.
`init "\\desktop-name\Network\test.exe"`
Would result in the first backslash being parsed out.
Despite that, the double quotes parsing code looks fine. Maybe I'm missing something here though.

commandparser handle UNC paths

---

src/dbg/plugin_loader.cpp
src/dbg/plugin_loader.h
src/exe/signaturecheck.cpp

Some plugins may contain multiple other libraries so the plugin folder becomes quite messy over time. This adds support to load plugins from a sub directory, ex.: `x64/plugins/myplugin/myplugin.dp64`.
The directory name MUST match the plugin name in order to work. I also refactored the way how pluginload and pluginunload works, one does not have to use `pluginload myplugin/myplugin.dp64` for it to work, providing just the plugin name is now the preferred way, plugins will also load when `pluginload myplugin.dp64` is used even when its from a sub directory. I personally think that the requirement of having the same name is sensible, having that not a requirement would add way more complexity and the command pluginload would have to always specify the relative path.
This PR also fixes …

Add support for plugins in sub directories

---

src/launcher/x64dbg_launcher.cpp

When x96dbg failed to open a file, it displayed a message box with the path as the message and a reason string as the caption. This looks weird, as the caption conveys useful information but it can usually be truncated.
We should display the reason string as the message, and the path as the caption instead.

Make error messages clearer if x96dbg fails to open a file

---

src/gui/Src/Gui/EditBreakpointDialog.cpp
src/gui/Src/Gui/EditBreakpointDialog.h

Should fix #3248
As I can see, one of the few things that this dialog does is escape double quotes. But it's done in the methods like `on_editLogText_textEdited`, which are obviously called only when something is actually updated. So if the user doesn't touch the text fields, they don't get escaped. The solution is to make this escaping mandatory as soon as the OK button is pressed.
Somewhat unrelated, I also made the window resizable horizontally. If I remember correctly, the maximum size of those text fields is 256 bytes, but the window has room only for ~42 characters by default.

Fixed a bug in the Edit Breakpoint dialog that might erase double quotes

---

src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/CPUDump.cpp
src/gui/Src/Gui/CPUStack.cpp
src/gui/Src/Gui/HexEditDialog.cpp
src/gui/Src/Gui/HexEditDialog.h
src/gui/Src/Gui/HexEditDialog.ui
src/gui/Src/Gui/MemoryMapView.cpp
src/gui/Src/Utils/Configuration.cpp

It didn't make sense for searches to begin from the current selection, nor was this obvious from the UI, maybe this was a bug.
The start/end of the search ranges are dependant on the users Memory Map view (Section or Region view), perhaps this should be made clear to the user somehow.
Disassembler: Search for -> Current Region -> Pattern (Ctrl + B)
Previous range: Selection -> End of Region
New range: Start of Region -> End of Region
Removed "Entire Block" checkbox
Dump: Find Pattern... (Ctrl + B)
Previous range: Selection -> End of Region
New range: Start of Region -> End of Region
Removed "Entire Block" checkbox
Stack: Find Pattern... (Ctrl + B)
Previous range: Selection -> End of Region
New range: Start of Region -> End of Region
Removed "Entire Block" checkbox
Memory Map: Find …

Find Pattern searches now begin at start of current region

---

src/bridge/bridgemain.cpp
src/bridge/bridgemain.h
src/dbg/commands/cmd-gui.cpp
src/dbg/commands/cmd-gui.h
src/dbg/x64dbg.cpp
src/gui/Src/Bridge/Bridge.cpp
src/gui/Src/Bridge/Bridge.h
src/gui/Src/Gui/BreakpointsView.cpp
src/gui/Src/Gui/CPUDisassembly.cpp
src/gui/Src/Gui/CallStackView.cpp
src/gui/Src/Gui/CallStackView.h
src/gui/Src/Gui/EditBreakpointDialog.cpp
src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/Gui/MainWindow.h
src/gui/Src/Gui/MemoryMapView.cpp
src/gui/Src/Gui/SimpleTraceDialog.cpp
src/gui/Src/Gui/SymbolView.cpp
src/gui/Src/Gui/ThreadView.cpp
src/gui/Src/Gui/ThreadView.h
src/gui/Src/Gui/XrefBrowseDialog.cpp
src/gui/Src/Utils/CommonActions.cpp
src/gui/Src/Utils/StringUtil.cpp
src/gui/Src/Utils/StringUtil.h

Adding `Follow in Threads` and `Rename Thread` option to context menu.
Solves #3232

#3232: Providing Rename Thread and etc. for CallStack View

---

src/dbg/TitanEngine/TitanEngine.txt
src/dbg/database.cpp
src/gui/Src/Gui/DisassemblerGraphView.cpp
src/gui/Src/Gui/SettingsDialog.cpp

Small changes to use gender neutral language and fix typos in code comments.

Use gender neutral language

---

src/gui/Src/Gui/GotoDialog.cpp
src/gui/Src/Gui/GotoDialog.ui

Had a crash course regarding Qt GUI...
The window now does not want to increase in size (somehow?, maybe by reducing the label width it got force shortened?), I have added max values to prevent expanding too much if it would happen.
Added a functionality to split a long symbol name with break lines based on the width of the editExpression.
Solves #3163 .

#3163: Long symbol name

---

src/dbg/_global.cpp
src/dbg/_global.h
src/dbg/analysis/AnalysisPass.cpp

Fixed very old problem on any Windows NT and modern Windows Server 😆 
https://developercommunity.visualstudio.com/t/hardware-concurrency-returns-an-incorrect-result/350854
https://stackoverflow.com/questions/31209256/reliable-way-to-programmatically-get-the-number-of-hardware-threads-on-windows
Why this commit is useful not only for server configurations, now a very cheap PC configuration is building from Xeon E54xx, X34xx, E3-xxxx, E5-xxxx, E7-xxx, any Silver, any Gold, any Platinum series, cheapest on LGA 2011v3 socket two-socket board with NUMA support is cheap on Alibaba, Baidu or Aliexpress and Amazon.
Examples:
https://www.alibaba.com/product-detail/DDR4-x99-dual-cpu-Lga2011-V3_1600443686429.html
https://www.amazon.com/Desktop-Motherboard-Gigabit-LGA2011-SATA3-0/dp/B0CC6KSTXC

Fixed get count threads for multi-cpu system with NUMA architecture

---

src/gui/Src/Gui/PageMemoryRights.cpp

It took ages for the dialog to show up when the section is large. The select all implementation was also very inefficient, now its all pretty much instant.
~~The change in MemGetPageRights is maybe not the most optimal thing, the change will cause it to prefer the cache if the debugger is paused which should be safe in like 99% unless something modifies it externally, in most cases the memory pages are updated when the user modifies anything from within x64dbg.~~
Can't use the cache as when bListAllPages is disabled its not allowed to split which would lead to having the wrong information in the page list, ideally the UI memory map builds its own view and the actual memory map reflects the actual pages.

Optimize select/deselect all in Page Rights UI

---

src/gui/Src/Gui/MainWindow.cpp
src/gui/Src/Utils/StringUtil.cpp

Escaping the `{` from file path for initalization of the debugger by pressing Open File or Drag&Drop or restarting.
Also, it allows for providing `{` as a normal character for any cmd argument that is needed to be escaped (`setthreadname`, `loadlib`, `BreakpointEdit`).
plz test :<
Closes #3238

#3238: Escaping { from any command argument

---

src/gui/Src/Gui/HandlesView.cpp

Double click should go to wndproc.
I also think we should start wrapping WIN32 API calls in #ifdef per #3224.

Double click to follow wndproc

---

src/gui/Src/Disassembler/ZydisTokenizer.cpp

`mInst.tokens.push_back(SingleToken(mIsNop ? TokenType::MnemonicNop : type, text, value));` 
This above line would make the additional space from `addToken(TokenType::Space, " ");` to be also `TokenType::MnemonicNop`.
(called from `bool ZydisTokenizer::tokenizeMnemonic(TokenType type, const QString & mnemonic)` [here](https://github.com/x64dbg/x64dbg/blob/009bff18c93da2f268fa52f0ceee2eea756fdb38/src/gui/Src/Disassembler/ZydisTokenizer.cpp#L501C4-L501C37) in the same file, making it highlightable later in the debugger.
https://github.com/x64dbg/x64dbg/assets/28221162/13dfda4e-7689-4e27-9310-e1f69ed31e38
https://github.com/x64dbg/x64dbg/assets/28221162/aafe217b-4a8d-4f2a-a061-74ca3eff07fd
https://github.com/x64dbg/x64dbg/assets/28221162/16f965ab-e2c7-405b-b67b-2efa11bb6ec1
Closes #3134 .

#3134: Avoiding having space in MnemonicNop instruction

---

src/gui/Src/Tracer/TraceRegisters.cpp
src/gui/Src/Tracer/TraceRegisters.h

Fixes #3050 
From the 'Trace' window, select a register value and set it as the current value. To do so, right click on the trace register value and select 'Set as current value'. This option would be available for any register that can be modified in the CPU registers window.

Set trace register value as current value

---

src/launcher/x64dbg_launcher.cpp

Windows supports HiDPI for dialog based application. It just needs to be enabled. And we can't use the manifest because it's shared with x32dbg.exe that has its own HiDPI policy.

Enable HiDPI for launcher

---

src/gui/Src/Gui/DisassemblerGraphView.cpp
src/gui/Src/Gui/DisassemblerGraphView.h

It seems there's a crash when saving graph image. Qt Creator outputs the log message:
```
QPaintDevice: Cannot destroy paint device that is being painted
QWidget::repaint: Recursive repaint detected
```
The newly downloaded snapshot also crashes when saving graph image.
Also the image formats WEBP and TIFF are added. The required file format plugins are already shipped, and WEBP image is smaller and lossless, so why not.

Save graph as WEBP and TIFF and fix crash

---

src/gui/Src/Tracer/TraceBrowser.cpp
src/gui/Src/Tracer/TraceFileDump.cpp
src/gui/Src/Tracer/TraceInfoBox.cpp
src/gui/Src/Tracer/TraceWidget.cpp
src/gui/Src/Tracer/TraceWidget.h

The ability to cancel loading dump also makes x64dbg crashes if the user cancels loading while x64dbg expects it to be loaded. So a return value check is now added.
The trace dump is freed in another thread so the trace can be closed fast.

fix crash and free dump in another thread

---

src/dbg/memory.cpp

24H2 adds hotpatching, with hotpatchable modules having an extra page mapped at the end of their image region. We previously assumed that the image region will only contain the header and executable sections, that's no longer the case.
Fixes #3338

Update image memory region processing to support 24H2 changes

---

src/launcher/x64dbg_launcher.cpp

These modes don't support dialog based application, so no need to use them. https://msdn.microsoft.com/library/mt843498(v=vs.85)

Remove high DPI modes incompatible with windows dialog

---

src/gui/Src/Tracer/TraceBrowser.cpp
src/gui/Src/Tracer/TraceBrowser.h
src/gui/Src/Tracer/TraceDump.cpp
src/gui/Src/Tracer/TraceFileDump.cpp
src/gui/Src/Tracer/TraceFileDump.h
src/gui/Src/Tracer/TraceFileReader.cpp
src/gui/Src/Tracer/TraceFileReader.h
src/gui/Src/Tracer/TraceFileReaderInternal.h
src/gui/Src/Tracer/TraceInfoBox.cpp
src/gui/Src/Tracer/TraceInfoBox.h
src/gui/Src/Tracer/TraceRegisters.cpp
src/gui/Src/Tracer/TraceRegisters.h
src/gui/Src/Tracer/TraceStack.cpp
src/gui/Src/Tracer/TraceWidget.cpp
src/gui/Src/Tracer/TraceWidget.h
src/gui/Src/Tracer/TraceXrefBrowseDialog.cpp
src/gui/Src/Tracer/TraceXrefBrowseDialog.h

Memory usage is reduced from 1.1GB to 999MB for a test trace.

Use 32-bit trace index to save memory

---

src/dbg/commands/cmd-searching.cpp
src/dbg/exprfunc.cpp
src/gui/Src/Tracer/TraceBrowser.cpp
src/gui/Src/Tracer/TraceDump.cpp
src/gui/Src/Tracer/TraceDump.h
src/gui/Src/Tracer/TraceFileDump.cpp
src/gui/Src/Tracer/TraceFileDump.h
src/gui/Src/Tracer/TraceFileReader.cpp
src/gui/Src/Tracer/TraceFileReader.h
src/gui/Src/Tracer/TraceFileReaderInternal.h
src/gui/Src/Tracer/TraceFileSearch.cpp
src/gui/Src/Tracer/TraceFileSearch.h
src/gui/Src/Tracer/TraceWidget.cpp
src/gui/Src/Tracer/TraceXrefBrowseDialog.cpp

Now you can find pattern in trace dump. The memory changes during the trace, and the match can be anywhere at anytime within the trace.
Since there is no unit test, please report incorrect results.

Find pattern in trace dump

---

src/gui/Src/BasicView/AbstractStdTable.cpp
src/gui/Src/BasicView/AbstractStdTable.h
src/gui/Src/Gui/MemoryMapView.cpp
src/gui/Src/Gui/MemoryMapView.h

Restoring the selection after the MMap is updated by holding the no. of row which was selected earlier.
https://github.com/x64dbg/x64dbg/assets/28221162/13551567-2e9b-45c5-bd9f-a71b3c78d072
Closes #3280 .

#3280: Selection shifts when MemoryMap is updated

---

src/dbg/_exports.cpp
src/dbg/debugger.cpp
src/dbg/debugger.h
src/gui/Src/Gui/AttachDialog.cpp
src/gui/Src/Gui/HandlesView.cpp
src/gui/Src/Gui/SettingsDialog.cpp
src/gui/Src/Gui/SettingsDialog.h
src/gui/Src/Gui/SettingsDialog.ui
src/gui/Src/Gui/ThreadView.cpp
src/gui/Src/Tracer/TraceInfoBox.cpp
src/gui/Src/Utils/Configuration.cpp

This PR removes `PidInHex` settings from Configuration and its uses. All of the TIDs/PIDs are being stored in decimal format.
Issue #3142.

Removing PidTidInHex, keeping PID/TID in dec

---

src/gui/Src/Gui/DisassemblerGraphView.cpp
src/gui/Src/Gui/DisassemblerGraphView.h

Loading current graph on the `GUI_UPDATE_GRAPH_VIEW` message, allowing `GuiUpdateAllViews` function to initiate a graph reloading (such as after adding a comment).
https://github.com/user-attachments/assets/51857072-4e62-4b26-9642-27d3b7209160
Closes #3397 .

Loading current graph in GUI_UPDATE_GRAPH_VIEW

---

src/dbg/_exports.cpp
src/dbg/debugger.cpp
src/dbg/simplescript.cpp
src/dbg/simplescript.h

Now it is able to use "scriptcmd call label" in breakpoint command.
There may be some hard to tell bugs. For example, x64dbg pops up "script finished" dialog when the last label is executed. Annoying, but it's difficult to tell whether this dialog should pop up.

Fix "scriptcmd call label" when script is not running

---

src/dbg/memory.cpp
src/dbg/ntdll/ntdll.h

From Windows 11 24H2, no all heap information exists in the PEB (only the first heap is stored).
So we must enumerate the entire heap along the process heap descriptor.
You can see https://cafe.naver.com/megayuchi/683 for more details

Update heap enumeration in Windows 11 24H2

---

src/dbg/expressionfunctions.cpp
src/dbg/exprfunc.cpp
src/dbg/exprfunc.h

This PR introduces the mem.cmp(address, "hex-byte-string") expression function, allowing users to compare memory at a given address with a specified byte sequence
Closes #3525 - `Add mem.cmp expression function to x64dbg`
- Added mem.cmp(address, "hex-byte-string") as an expression function.
- Parses the hex string into bytes and compares it with memory contents at the specified address.
- (On odd-length hex inputs, a prefix `0` is assumed, will need feedback if that part is reasonable.)
- Returns `0` if memory matches, positive and negative otherwise, refer to [memcmp](https://www.man7.org/linux/man-pages/man3/memcmp.3.html) for return value.
Makes weird workarounds like `byte(ptr) == .... && ... && byte(ptr+n) = ...` obsolete and allows convenient memory comparison inside breakpoint …

Add mem.cmp Expression Function for Memory Comparison

---

src/dbg/stringformat.cpp

Oh no, I can’t believe I just wrote that code that causes a crash, right next to something "prevent buffer overflow". This is only discovered when upgrading this feature to support AVX512.

Fix buffer overflow

---

src/gui/Src/Gui/CPUDisassembly.cpp

When adding AVX512 support for this feature, I found these icons are all the same, caused by DIcon.

Fix wrong icon for ActionTreatSelectionAsXXX

---

src/launcher/x64dbg_launcher.cpp

This avoids having to re-start x96dbg on first run (when x96dbg.ini has not been initialized).

Show launcher on first launch after installing

---

src/gui/Src/Gui/DisassemblerGraphView.cpp
src/gui/Src/Gui/DisassemblerGraphView.h
src/gui/Src/Utils/Configuration.cpp

The user can copy the image in addition to save image. However, the copied image may have different resolution with saved image due to HiDPI settings.

Copy graph image
